Imports DevExpress.XtraGrid.Views.Base
Imports DevExpress.XtraGrid.Views.Grid
Imports DevExpress.XtraGrid.Columns
Imports System.Data.Odbc

Public Class POInternalDesign
    Dim s, c As String
    Dim filter As Boolean
    Dim brske, brspo As Integer
    Dim LoadDT As String
    Dim Proses As String
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill the SqlDataSource asynchronously
        SqlDataSource1.FillAsync()
    End Sub

#Region " Deklarasi  Listview"
    Private Sub ListHeadDsn()
        ListPODsn.FullRowSelect = True
        ListPODsn.MultiSelect = True
        ListPODsn.View = View.Details
        ListPODsn.CheckBoxes = True
        ListPODsn.Columns.Clear()
        ListPODsn.Items.Clear()
        ListPODsn.Columns.Add("NO.PO", 150, HorizontalAlignment.Left)
        ListPODsn.Columns.Add("TANGGAL", 110, HorizontalAlignment.Left)
        ListPODsn.Columns.Add("KLIEN", 200, HorizontalAlignment.Left)
        ListPODsn.Columns.Add("BRAND", 150, HorizontalAlignment.Left)
        ListPODsn.Columns.Add("NOPE", 200, HorizontalAlignment.Left)
        ListPODsn.Columns.Add("idpo", 0, HorizontalAlignment.Left)
        ListPODsn.Columns.Add("iddsn", 0, HorizontalAlignment.Left)
        ListPODsn.Columns.Add("DEADLINE", 150, HorizontalAlignment.Left)
        ListPODsn.Columns.Add("iddtorder", 0, HorizontalAlignment.Left)
        ListPODsn.Columns.Add("STATUS", 150, HorizontalAlignment.Left)
        ListPODsn.Columns.Add("PO PRODUKSI", 150, HorizontalAlignment.Left)
    End Sub

    Private Sub ListHeadDetail()
        ListDetailPODsn.FullRowSelect = True
        ListDetailPODsn.MultiSelect = True
        ListDetailPODsn.View = View.Details
        ListDetailPODsn.CheckBoxes = True
        'ListDetailPODsn.SmallImageList = ImgList
        ListDetailPODsn.Columns.Clear()
        ListDetailPODsn.Items.Clear()
        ListDetailPODsn.Columns.Add("TOKO", 180, HorizontalAlignment.Left)
        ListDetailPODsn.Columns.Add("KOTA", 120, HorizontalAlignment.Left)
        ListDetailPODsn.Columns.Add("BARANG", 200, HorizontalAlignment.Left)
        ListDetailPODsn.Columns.Add("BRAND", 100, HorizontalAlignment.Left)
        ListDetailPODsn.Columns.Add("P", 60, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("L", 60, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("T", 60, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("SISI", 60, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("JML", 60, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("IDBARANG", 0, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("IDPOPRD", 0, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("IDTOKO", 0, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("IDDTORDER", 0, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("IDDETAILDSN", 0, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("KETERANGAN", 150, HorizontalAlignment.Right)
    End Sub

    Private Sub ListHeadPrint()
        ListPOPrint.FullRowSelect = True
        ListPOPrint.MultiSelect = True
        ListPOPrint.View = View.Details
        ListPOPrint.CheckBoxes = True
        ListPOPrint.Columns.Clear()
        ListPOPrint.Items.Clear()
        ListPOPrint.Columns.Add("TOKO", 180, HorizontalAlignment.Left)
        ListPOPrint.Columns.Add("BARANG", 200, HorizontalAlignment.Left)
        ListPOPrint.Columns.Add("P", 60, HorizontalAlignment.Right)
        ListPOPrint.Columns.Add("L", 60, HorizontalAlignment.Right)
        ListPOPrint.Columns.Add("T", 60, HorizontalAlignment.Right)
        ListPOPrint.Columns.Add("JML", 60, HorizontalAlignment.Right)
        ListPOPrint.Columns.Add("iditem_prt", 0, HorizontalAlignment.Right)
        ListPOPrint.Columns.Add("iddetail_po_prt", 0, HorizontalAlignment.Right)
        ListPOPrint.Columns.Add("idtoko", 0, HorizontalAlignment.Right)
        ListPOPrint.Columns.Add("BAHAN", 110, HorizontalAlignment.Right)
        ListPOPrint.Columns.Add("FINISHING", 150, HorizontalAlignment.Right)
    End Sub
#End Region
#Region "Deklarasi Fungsi"
    Private Sub TampilPODesain()

        Dim s As String
        Dim i As Integer
        Dim tbl As New DataTable

        ListPODsn.Items.Clear()
        ListDetailPODsn.Items.Clear()
        GGVM_conn()
        s = ""
        s = s & " select * from view_podesain"
        If RbTerima.Checked = True Then
            s = s & " WHERE isnull(terima_po_dsn) "
        ElseIf RbKirim.Checked = True Then
            s = s & " WHERE terima_po_dsn is not null "
            If FilterPekerjaan.Checked = True Then
                s = s & " and time_closhing_dsn is not null and terima_po_dsn is not null and selesai_desain is not null"
            ElseIf CbOnprogress.Checked = True Then
                s = s & " and time_closhing_dsn is null and  terima_po_dsn is not null and kirim_po_dsn is not null"
            Else
                s = s & " and time_closhing_dsn is null and terima_po_dsn is not null and kirim_po_dsn is null"
            End If
        End If
        s = s & " ORDER BY kirim_po_dsn DESC "
        da = New System.Data.Odbc.OdbcDataAdapter(s, conn)
        'ds.Clear()
        tbl = New DataTable
        tbl.Clear()
        da.Fill(tbl)

        For i = 0 To tbl.Rows.Count - 1
            Dim statuspekerjaan As String = ""
            If IIf(IsDBNull(tbl.Rows(i)("time_closhing_dsn")).ToString, "", tbl.Rows(i)("time_closhing_dsn")).ToString = "" And IIf(IsDBNull(tbl.Rows(i)("kirim_po_dsn")).ToString, "", tbl.Rows(i)("kirim_po_dsn")).ToString <> "" And IIf(IsDBNull(tbl.Rows(i)("terima_po_dsn")).ToString, "", tbl.Rows(i)("terima_po_dsn")).ToString <> "" Then
                statuspekerjaan = "On Progress"
            ElseIf IIf(IsDBNull(tbl.Rows(i)("time_closhing_dsn")).ToString, "", tbl.Rows(i)("time_closhing_dsn")).ToString <> "" And IIf(IsDBNull(tbl.Rows(i)("terima_po_dsn")).ToString, "", tbl.Rows(i)("terima_po_dsn")).ToString <> "" Then
                statuspekerjaan = "Selesai"
            ElseIf IIf(IsDBNull(tbl.Rows(i)("terima_po_dsn")).ToString, "", tbl.Rows(i)("terima_po_dsn")).ToString <> "" And IIf(IsDBNull(tbl.Rows(i)("time_closhing_dsn")).ToString, "", tbl.Rows(i)("time_closhing_dsn")).ToString = "" Then
                statuspekerjaan = "Diterima"
            Else
                statuspekerjaan = "Belum diTerima"
            End If
            With ListPODsn
                .Items.Add(tbl.Rows(i)("nopo_dsn"))
                With .Items(.Items.Count - 1).SubItems
                    .Add(IIf(IsDBNull(tbl.Rows(i)("tanggalpo_dsn")), "", tbl.Rows(i)("tanggalpo_dsn")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("klien")), "", tbl.Rows(i)("klien")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("brand")), "", tbl.Rows(i)("brand")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("nope")), "", tbl.Rows(i)("nope")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("idpo_prd")), "", tbl.Rows(i)("idpo_prd")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("idpo_dsn")), "", tbl.Rows(i)("idpo_dsn")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("deadline_desain")), "", tbl.Rows(i)("deadline_desain")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("iddtorder")), "", tbl.Rows(i)("iddtorder")))
                    .Add(statuspekerjaan)
                    .Add(tbl.Rows(i)("PO_Produksi"))
                End With
            End With
        Next
        GGVM_conn_close()
    End Sub
    Private Sub TampilPODeTAIL()

        Dim s As String
        Dim i As Integer
        Dim tbld As New DataTable

        ListDetailPODsn.Items.Clear()
        ListPOPrint.Items.Clear()
        GGVM_conn()
        s = ""
        s = s & " SELECT * from view_detailpo_dsn "
        s = s & " WHERE idpo_dsn ='" & ListPODsn.Items(brspo).SubItems(6).Text & "' "
        'If filter = True Then
        '    s = s & " and kirim_po is not null and kirim_ppic is not null"
        'Else
        '    s = s & " and kirim_po is null and kirim_ppic is null"
        'End If

        ' s = s & " WHERE idpo_prd ='" & TidPO.Text & "'"
        da = New OdbcDataAdapter(s, conn)
        'ds.Clear()
        tbld = New DataTable
        tbld.Clear()
        da.Fill(tbld)
        For i = 0 To tbld.Rows.Count - 1
            With ListDetailPODsn
                .Items.Add(tbld.Rows(i)("toko"))
                With .Items(.Items.Count - 1).SubItems
                    .Add(tbld.Rows(i)("kota"))
                    .Add(tbld.Rows(i)("barang"))
                    .Add(tbld.Rows(i)("brand"))
                    .Add(Int(Val(tbld.Rows(i)("panjang_prd"))))
                    .Add(Int(Val(tbld.Rows(i)("lebar_prd"))))
                    .Add(Int(Val(tbld.Rows(i)("tinggi_prd"))))
                    .Add(Int(Val(tbld.Rows(i)("sisi_prd"))))
                    .Add(Int(Val(tbld.Rows(i)("qty_prd"))))
                    .Add(tbld.Rows(i)("idbarang"))
                    .Add(tbld.Rows(i)("idpo_dsn"))
                    .Add(IIf(IsDBNull(tbld.Rows(i)("idtoko")), "", tbld.Rows(i)("idtoko")))
                    .Add(tbld.Rows(i)("iddtorder"))
                    .Add(tbld.Rows(i)("iddetail_dsn"))
                    .Add(IIf(IsDBNull(tbld.Rows(i)("keterangan")), "", tbld.Rows(i)("keterangan")))
                End With
            End With
        Next
        'GGVM_conn_close()
    End Sub
    Private Sub TampilDetailPrinting()
        Dim s As String
        Dim i As Integer
        Dim tbl As New DataTable

        ListPOPrint.Items.Clear()
        GGVM_conn()
        s = ""
        s = s & " select * from view_detailpo_printing "
        s = s & " where idtoko = '" & TIdToko.Text & "' and iddetail_dsn='" & ListDetailPODsn.Items(brske).SubItems(13).Text & "' "
        da = New OdbcDataAdapter(s, conn)
        'ds.Clear()
        tbl = New DataTable
        tbl.Clear()
        da.Fill(tbl)
        For i = 0 To tbl.Rows.Count - 1
            With ListPOPrint
                .Items.Add(tbl.Rows(i)("toko"))
                With .Items(.Items.Count - 1).SubItems
                    .Add(tbl.Rows(i)("barang"))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("panjang_prt")), "", tbl.Rows(i)("panjang_prt")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("lebar_prt")), "", tbl.Rows(i)("lebar_prt")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("tinggi_prt")), "", tbl.Rows(i)("tinggi_prt")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("qty_prt")), "", tbl.Rows(i)("qty_prt")))
                    .Add(tbl.Rows(i)("idbarang"))
                    .Add(tbl.Rows(i)("iddetail_po_prt"))
                    If tbl.Rows(i)("idtoko") Is DBNull.Value Then
                        .Add("0")
                    Else
                        .Add(tbl.Rows(i)("idtoko"))
                    End If
                    .Add(IIf(IsDBNull(tbl.Rows(i)("bahan")), "", tbl.Rows(i)("bahan")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("finishing")), "", tbl.Rows(i)("finishing")))
                    .Add(tbl.Rows(i)("idbahan"))
                    .Add(tbl.Rows(i)("idfinishing"))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("idpo_prt")), "", tbl.Rows(i)("idpo_prt")))
                End With
            End With
        Next
        GGVM_conn_close()
    End Sub


    Private Sub AutoCompBarangPrinting()

        Try
            GGVM_conn()
            s = ""
            s = s & " select * from ("
            s = s & " select barang_int,idbarang_int from barang"
            s = s & " where idsubkel = 79"
            's = s & " and barang like '%" & TBarang2.Text & "%'"
            s = s & " group by barang_int ) y"
            da = New OdbcDataAdapter(s, conn)
            ds = New DataSet
            da.Fill(ds)
            Dim BarangPrinting As New AutoCompleteStringCollection
            For i As Integer = 0 To ds.Tables(0).Rows.Count - 1
                BarangPrinting.Add(ds.Tables(0).Rows(i)("barang_int"))
            Next
            With TBarang2
                .AutoCompleteSource = AutoCompleteSource.CustomSource
                .AutoCompleteCustomSource = BarangPrinting
                .AutoCompleteMode = AutoCompleteMode.Suggest
            End With
        Catch ex As Exception
            MsgBox("Terjadi kesalahan! " & ex.Message)
        End Try
        GGVM_conn_close()
    End Sub
    Private Sub AutoCompFinishing()
        Try
            GGVM_conn()
            s = ""
            s = s & " select finishing from prd_finishing_printing "
            da = New OdbcDataAdapter(s, conn)
            ds = New DataSet
            da.Fill(ds)
            Dim FinishingItem As New AutoCompleteStringCollection
            For i As Integer = 0 To ds.Tables(0).Rows.Count - 1
                FinishingItem.Add(ds.Tables(0).Rows(i)("finishing"))
            Next
            With TFinishing
                .AutoCompleteSource = AutoCompleteSource.CustomSource
                .AutoCompleteCustomSource = FinishingItem
                .AutoCompleteMode = AutoCompleteMode.Suggest
            End With
        Catch ex As Exception
            MsgBox("Terjadi kesalahan! " & ex.Message)
        End Try
        GGVM_conn_close()
    End Sub
    Private Sub EntryMode()
        TToko.Enabled = False
        TBarang1.Enabled = False
        TBrand.Enabled = False
        Tp1.Enabled = False
        Tl1.Enabled = False
        Tt1.Enabled = False
        TKota.Enabled = False
        TBarang2.Enabled = True
        Tp2.Enabled = True
        Tl2.Enabled = True
        Tt2.Enabled = True
        CPrinting.Enabled = True
        BtnSimpanDetail.Enabled = True
        BtnSimpanDetail.Text = "Simpan"
        ListPOPrint.Enabled = False
        BtnEditDsn.Enabled = False
        BtnEntryDsn.Enabled = False
    End Sub
    Private Sub LoadBahan()
        Dim s As String
        CBahan.Items.Clear()
        GGVM_conn()
        s = ""
        s = s & "select bahan from prd_bahan_printing"
        da = New OdbcDataAdapter(s, conn)
        'ds.Clear()
        dt = New DataTable
        dt.Clear()
        da.Fill(dt)

        For i = 0 To dt.Rows.Count - 1
            With CBahan
                .Items.Add(dt.Rows(i)("bahan"))
            End With
        Next
        GGVM_conn_close()
    End Sub
    Private Sub tutupdesain()
        TToko.Text = ""
        TBarang1.Text = ""
        TBrand.Text = ""
        Tp1.Text = ""
        Tl1.Text = ""
        Tt1.Text = ""
        Tj1.Text = ""
        TIdBarang1.Text = ""
        TidPO.Text = ""
        TIdToko.Text = ""
        TIdBrand.Text = ""
        TBarang2.Text = ""
        TIdBarang2.Text = ""
        'C.TBarang.Text = ""
        Tp2.Text = "0"
        Tl2.Text = "0"
        Tt2.Text = "0"
        Tj2.Text = "0"
        TidBahan.Text = ""
        CBahan.Text = ""
        TFinishing.Text = ""
        CPrinting.Enabled = False
        ListPOPrint.Enabled = True
        BtnEditDsn.Enabled = False
        BtnEntryDsn.Enabled = True
    End Sub
#End Region
    Private Sub POInternalDesign_Load(sender As Object, e As EventArgs) Handles Me.Load
        ListHeadDsn()
        ListHeadDetail()
        ListHeadPrint()
        TampilPODesain()
        RbTerima.Checked = True
        BtnAccDsn.Caption = "TERIMA PO"
    End Sub


    Private Sub RbTerima_CheckedChanged(sender As Object, e As EventArgs) Handles RbTerima.CheckedChanged
        If RbTerima.Checked = True Then
            BtnAccDsn.Enabled = True
            BtnAccDsn.Caption = "TERIMA PO"
            BtnAccDsn.DropDownEnabled = False
            TampilPODesain()
            FilterPekerjaan.Enabled = False
            CbOnprogress.Enabled = False
            BtnSelesai.Enabled = False
        End If
    End Sub

    Private Sub RbKirim_CheckedChanged(sender As Object, e As EventArgs) Handles RbKirim.CheckedChanged
        If RbKirim.Checked = True Then
            BtnAccDsn.Enabled = True
            BtnAccDsn.Caption = "KIRIM PO"
            BtnAccDsn.DropDownEnabled = True
            TampilPODesain()
            FilterPekerjaan.Enabled = True
            CbOnprogress.Enabled = True
            BtnSelesai.Enabled = True
        End If
    End Sub


    Private Sub TFinishing_TextChanged(sender As Object, e As EventArgs) Handles TFinishing.TextChanged
        Try
            GGVM_conn()
            s = " select * from prd_finishing_printing where finishing =  '" & TFinishing.Text & "' "
            cmd = New OdbcCommand(s, conn)
            dr = cmd.ExecuteReader
            dr.Read()
            If Not dr.HasRows Then
                TidFinishing.Text = ""
            Else
                TidFinishing.Text = dr.Item("idfinishing")
            End If
        Catch ex As Exception
            MsgBox("Terjadi kesalahan! " & ex.Message)
        End Try
        GGVM_conn_close()
    End Sub
    Private Sub TBarang2_TextChanged(sender As Object, e As EventArgs) Handles TBarang2.TextChanged
        Try
            GGVM_conn()
            s = " select * from barang where barang_int =  '" & TBarang2.Text & "' "
            cmd = New OdbcCommand(s, conn)
            dr = cmd.ExecuteReader
            dr.Read()
            If Not dr.HasRows Then
                TIdBarang2.Text = ""
            Else
                TIdBarang2.Text = dr.Item("idbarang_int")
            End If
        Catch ex As Exception
            MsgBox("Terjadi kesalahan! " & ex.Message)
        End Try
        GGVM_conn_close()
    End Sub
    Private Sub BtnEntryDsn_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BtnEntryDsn.ItemClick
        Dim ada, item As Boolean
        Dim jmldt, jmldetail, brs2 As Integer
        ada = False
        item = False
        jmldt = 0
        If TidPoDsn.Text = "" Then
            MsgBox("Tidak ada data PO yang akan di Entry, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
            Exit Sub
        End If
        If TidDetailDsn.Text = "" Then
            MsgBox("Tidak ada data Detail yang akan dipilih, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
            Exit Sub
        End If
        For i = 0 To ListDetailPODsn.Items.Count - 1
            If ListDetailPODsn.Items(i).Checked = True Then
                item = True
                brs2 = i
                jmldetail = jmldetail + 1
            End If
        Next
        If item = False Then
            MsgBox("Tidak ada data yang akan dipilih, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
            ListDetailPODsn.Focus()
            Exit Sub
        End If
        If jmldetail > 1 Then
            MsgBox("Hanya 1(satu) data PO-DESAIN yg bisa di-Entry !!...", MsgBoxStyle.Information, "Information")
            Exit Sub
        End If
        'Panel1.Visible = True
        AutoCompBarangPrinting()

        AutoCompFinishing()
        For i = 0 To ListDetailPODsn.Items.Count - 1
            If ListDetailPODsn.Items(i).Checked = True Then
                brs2 = i

                TToko.Text = ListDetailPODsn.Items(i).SubItems(0).Text
                TKota.Text = ListDetailPODsn.Items(i).SubItems(1).Text
                TBarang1.Text = ListDetailPODsn.Items(i).SubItems(2).Text
                TBrand.Text = ListDetailPODsn.Items(i).SubItems(3).Text
                Tp1.Text = ListDetailPODsn.Items(i).SubItems(4).Text
                Tl1.Text = ListDetailPODsn.Items(i).SubItems(5).Text
                Tt1.Text = ListDetailPODsn.Items(i).SubItems(6).Text
                Tj1.Text = ListDetailPODsn.Items(i).SubItems(8).Text
                TIdBarang1.Text = ListDetailPODsn.Items(i).SubItems(9).Text
                TidPO.Text = ListDetailPODsn.Items(i).SubItems(10).Text
                TIdToko.Text = ListDetailPODsn.Items(i).SubItems(11).Text
                TKeterangan.Text = ListDetailPODsn.Items(i).SubItems(14).Text
                'CBarang.Checked = False
                TBarang2.Text = ""
                'C.TBarang.Text = ""
                Tp2.Text = Val(Tp1.Text) + 5
                Tl2.Text = Val(Tl1.Text) + 5
                Tt2.Text = Val(Tt1.Text) + 5
                Tj2.Text = Val(Tj1.Text) + 5
                LoadBahan()
            End If
        Next
        Panel2.Visible = True
        EntryMode()
        Proses = "Entry"
    End Sub


    Private Sub BtnExitDsn_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BtnExitDsn.ItemClick
        If BtnExitDsn.Caption = "HAPUS" Then
            If MsgBox("Apakah anda yakin untuk menghapus detail Printing ?..", MsgBoxStyle.YesNo, "Question") = MsgBoxResult.Yes Then
                s = ""
                s = s & " update prd_detail_printing set isdelete='Y' "
                s = s & " where iddetail_po_prt ='" & TidDetailPoPrt.Text & "'"
                cmd = New OdbcCommand(s, conn)
                cmd.ExecuteNonQuery()
                BtnExitDsn.Caption = "KELUAR"
                TampilDetailPrinting()
            Else
                BtnExitDsn.Caption = "KELUAR"
            End If
        Else
            Me.Dispose()
        End If
    End Sub

    Private Sub BtnCetakPO_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BtnCetakPO.ItemClick
        If ListPODsn.Items(brspo).SubItems(5).Text = "" Then
            MsgBox("Tidak ada data PO-INTERNAL yg dicetak, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
            Exit Sub
        End If

        Me.Cursor = Cursors.WaitCursor


        'Dim report As New XtraReport
        'report = New ReportPOInternalDesain
        ' Obtain a parameter and set its value.
        'report.Parameters("idpo_dsn").Value = idpo

        ' Hide the Parameters' UI from end-users (if you did not hide it at design time).
        'report.Parameters("idpe").Visible = False

        Me.Cursor = Cursors.Default
        ' report.ShowPreview()
    End Sub
    Private Sub CPrinting_CheckedChanged(sender As Object, e As EventArgs) Handles CPrinting.CheckedChanged
        If CPrinting.Checked = True Then
            PanelP.Visible = True
        Else
            PanelP.Visible = False
            Tt2.Text = "0"
            Tl2.Text = "0"
            Tp2.Text = "0"
            Tj2.Text = "0"
        End If
    End Sub
    Private Sub TidDetailPoPrt_TextChanged(sender As Object, e As EventArgs) Handles TidDetailPoPrt.TextChanged

        GGVM_conn()
        Try
            s = " select * from view_detailpo_printing where iddetail_po_prt =  '" & TidDetailPoPrt.Text & "' and idpo_prt is null"
            cmd = New OdbcCommand(s, conn)
            dr = cmd.ExecuteReader
            dr.Read()
            If Not dr.HasRows Then
                Tp2.Text = ""
                Tt2.Text = ""
                Tl2.Text = ""
                Tj2.Text = ""
                TBarang2.Text = ""
                ' TIdBarang2.Text = ""
            Else
                Tp2.Text = dr.Item("panjang_prt")
                Tt2.Text = dr.Item("tinggi_prt")
                Tl2.Text = dr.Item("lebar_prt")
                Tj2.Text = dr.Item("qty_prt")
                TBarang2.Text = dr.Item("barang")
                'TIdBarang2.Text = dr.Item("iditem_prd")
            End If
        Catch ex As Exception
            MsgBox("Terjadi kesalahan! " & ex.Message)
        End Try
    End Sub
    Private Sub ListPOPrint_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ListPOPrint.SelectedIndexChanged
        Me.Cursor = Cursors.WaitCursor
        With Me.ListPOPrint
            For Each check As ListViewItem In ListPOPrint.CheckedItems
                check.Checked = False
            Next
            For Each item As ListViewItem In ListPOPrint.SelectedItems
                item.Checked = True
                brske = item.Index
            Next
            TidDetailPoPrt.Text = ListPOPrint.Items(brske).SubItems(7).Text
            BtnExitDsn.Caption = "HAPUS"
            BtnEditDsn.Enabled = True
        End With
        'TampilDetailPrinting()
        Me.Cursor = Cursors.Default
    End Sub


    Private Sub BtnSimpanAlasan_Click(sender As Object, e As EventArgs) Handles BtnSimpanAlasan.Click
        If Len(Me.TAlasan.Text) < 10 Or Len(Me.TAlasan.Text) > 150 Then
            MsgBox("Alasan Terlalu Pendek, Minimal 10 Huruf !", MsgBoxStyle.Information, "Information !!")
            Exit Sub
        Else
            GGVM_conn()

        End If
        If CPrinting.Checked = True Then
            'c = ""
            'c = c & " update po_printing set "
            'c = c & " user_edit = '" & userid & "',"
            'c = c & " timeedit = now()"
            'c = c & " where idpo_prt = '" & TidPoPrt.Text & "'"
            'cmd = New OdbcCommand(c, conn)
            'cmd.ExecuteNonQuery()

            'sql = ""
            'sql = sql & "insert into prd_revisi_detail_po_printing (iddetail_po_prt,idpo_prt,idtoko,iditem_prt,item_prt,idsatuan,keterangan,panjang_prd, "
            'sql = sql & " tinggi_prd,lebar_prd,sisi_prd,qty_prd,panjang_prt,tinggi_prt,lebar_prt,sisi_prt,qty_prt,idfinishing,idbahan,iddetail_dsn, "
            'sql = sql & " isdelete,time_start,time_end,time_temp,done)  select * from prd_detail_po_printing WHERE iddetail_po_prt =  '" & TidDetailPoPrt.Text & "'"
            'cmd = New OdbcCommand(sql, conn)
            'cmd.ExecuteNonQuery()

            'c = ""
            'c = c & " insert into prd_revisi_po_printing (iddetail_po_prt,alasan,timerevisi,userrevisi) "
            'c = c & " values ('" & TidDetailPoPrt.Text & "', '" & TAlasan.Text & "', now(),'" & userid & "' ) "
            'cmd = New OdbcCommand(c, conn)
            'cmd.ExecuteNonQuery()

            's = ""
            's = s & " select max(idrevisi) as id from prd_revisi_po_printing where iddetail_po_prt ='" & TidDetailPoPrt.Text & "'"
            'da = New OdbcDataAdapter(s, conn)
            'dt = New DataTable
            'dt.Clear()
            'da.Fill(dt)
            'idrevisi.Text = dt.Rows(0)("id")

            'sql = ""
            'sql = sql & " update prd_revisi_detail_po_printing set idrevisi = '" & idrevisi.Text & "' "
            'sql = sql & " where iddetail_po_prt = '" & TidDetailPoPrt.Text & "' and idrevisi is null "
            'cmd = New OdbcCommand(sql, conn)
            'cmd.ExecuteNonQuery()


            'sql = ""
            'sql = sql & " select max(revisike)as idrev  from prd_revisi_po_printing where iddetail_po_prt = '" & TidDetailPoPrt.Text & "'"
            'da = New OdbcDataAdapter(sql, conn)
            'dt = New DataTable
            'dt.Clear()
            'da.Fill(dt)
            'Dim count As Integer
            'If dt.Rows(0)("idrev") = "1" Then
            '    count = 1
            'Else
            '    count = 0
            'End If
            'count = dt.Rows(0)("idrev") + 1

            'c = ""
            'c = c & "update prd_revisi_po_printing set revisike ='" & count & "' where idrevisi ='" & idrevisi.Text & "'"
            'cmd = New OdbcCommand(c, conn)
            'cmd.ExecuteNonQuery()

            c = ""
            c = c & " update prd_detail_po_printing set "
            c = c & " idbarang = '" & TIdBarang2.Text & "',"
            c = c & " panjang_prd = '" & Tp1.Text & "', "
            c = c & " tinggi_prd = '" & Tt1.Text & "', "
            c = c & " lebar_prd = '" & Tl1.Text & "', "
            c = c & " qty_prd = '" & Tj1.Text & "', "
            c = c & " panjang_prt = '" & Tp2.Text & "', "
            c = c & " tinggi_prt = '" & Tt2.Text & "', "
            c = c & " lebar_prt = '" & Tl2.Text & "', "
            c = c & " qty_prt = '" & Tj2.Text & "' , "
            c = c & " idbahan = '" & TidBahan.Text & "' , "
            c = c & " idfinishing = '" & TidFinishing.Text & "' "
            c = c & " where iddetail_po_prt = '" & TidDetailPoPrt.Text & "'"
            cmd = New OdbcCommand(c, conn)
            cmd.ExecuteNonQuery()
            Me.Cursor = Cursors.Default
        End If

        MsgBox("Data PO sudah di-Update !!..", MsgBoxStyle.Information, "Information")
        GGVM_conn_close()
        Panel2.Visible = False
        PanelAlasan.Visible = False
        TAlasan.Text = ""
        TampilDetailPrinting()
        Proses = "Entry"
        tutupdesain()
    End Sub

    Private Sub BtnClose_Click(sender As Object, e As EventArgs) Handles BtnClose.Click
        Panel2.Visible = False

        tutupdesain()
    End Sub

    Private Sub BtnSimpanDetail_Click(sender As Object, e As EventArgs) Handles BtnSimpanDetail.Click
        Select Case Proses
            Case "Entry"
                GGVM_conn()
                If TBarang2.Text = "" Then
                    MsgBox("Isi Dulu Barang-Nya .. !!", MsgBoxStyle.Information, "Pemberitahuan")
                    Exit Sub
                ElseIf CPrinting.Checked = False Then
                    MsgBox("Pilih Salah satu Printing / Cutting .. !!", MsgBoxStyle.Information, "Pemberitahuan")
                    Exit Sub
                ElseIf TidBahan.Text = "" Then
                    MsgBox("Bahan Tidak ada , Harap diisi dulu .. !! ", MsgBoxStyle.OkOnly, "Pemberitahuan")
                    Exit Sub
                ElseIf TIdBarang2.Text = "" Then
                    Dim kd As String

                    sql = ""
                    sql = sql & " select * from barang where barang_int = '" & TBarang2.Text & "' "
                    cmd = New OdbcCommand(sql, conn)
                    dr = cmd.ExecuteReader
                    dr.Read()
                    If Not dr.HasRows Then
                        'Count Kode Barang
                        s = ""
                        s = s & " Select max(idbarang_int)As id from barang"
                        cmd = New OdbcCommand(s, conn)
                        dr = cmd.ExecuteReader
                        dr.Read()
                        kd = "000000" + dr.GetString(0)
                        kd = Microsoft.VisualBasic.Right(kd, 6)

                        c = ""
                        c = c & "insert barang (idsubkel,kdbarang_int,barang_int,keterangan_brgint)"
                        c = c & "values ('79', '" & kd & "' , '" & TBarang2.Text & "', 'Otomatis') "
                        cmd = New OdbcCommand(c, conn)
                        cmd.ExecuteNonQuery()

                        c = ""
                        c = c & " Select max(idbarang_int) As id from barang "
                        da = New OdbcDataAdapter(c, conn)
                        dt = New DataTable
                        da.Fill(dt)
                        If dt.Rows.Count > 0 Then
                            TIdBarang2.Text = dt.Rows(0)("id")
                        End If
                    Else
                        MsgBox("BARANG SUDAH ADA .. !!", MsgBoxStyle.Information, "Pemberitahuan")
                        Exit Sub
                    End If
                ElseIf TidFinishing.Text = "" Then
                    s = ""
                    s = s & " insert into prd_finishing_printing ( finishing ) values ('" & TFinishing.Text & "')"
                    cmd = New OdbcCommand(s, conn)
                    cmd.ExecuteNonQuery()

                    c = ""
                    c = c & " Select max(idfinishing) As id from prd_finishing_printing "
                    da = New OdbcDataAdapter(c, conn)
                    dt = New DataTable
                    da.Fill(dt)
                    If dt.Rows.Count > 0 Then
                        TidFinishing.Text = dt.Rows(0)("id")
                    End If
                ElseIf TidBahan.Text = "" Then
                    s = ""
                    s = s & " insert into prd_bahan_printing ( bahan ) values ('" & CBahan.Text & "')"
                    cmd = New OdbcCommand(s, conn)
                    cmd.ExecuteNonQuery()

                    c = ""
                    c = c & " Select max(idbahan) As id from prd_bahan_printing "
                    da = New OdbcDataAdapter(c, conn)
                    dt = New DataTable
                    da.Fill(dt)
                    If dt.Rows.Count > 0 Then
                        TidBahan.Text = dt.Rows(0)("id")
                    End If
                End If
                If CPrinting.Checked = True Then
                    c = ""
                    c = c & " insert into prd_detail_po_printing (idtoko,idbarang,"
                    c = c & "  panjang_prt,tinggi_prt,lebar_prt, "
                    If CMal.Checked = True Then
                        c = c & " keterangan, "
                    End If
                    c = c & " qty_prt,iddetail_dsn,idfinishing,idbahan) values "
                    c = c & " ('" & TIdToko.Text & "','" & TIdBarang2.Text & "','" & Tp2.Text & "','" & Tt2.Text & "','" & Tl2.Text & "', "
                    If CMal.Checked = True Then
                        c = c & " 'MAL', "
                    End If
                    c = c & " '" & Tj2.Text & "','" & ListDetailPODsn.Items(brske).SubItems(13).Text & "','" & TidFinishing.Text & "','" & TidBahan.Text & "')"
                    cmd = New OdbcCommand(c, conn)
                    cmd.ExecuteNonQuery()
                    Me.Cursor = Cursors.Default
                End If

                MsgBox("Data PO sudah di-SIMPAN !!..", MsgBoxStyle.Information, "Information")
                GGVM_conn_close()
                'Panel1.Visible = False
                TampilDetailPrinting()
                TBarang2.Text = ""
                TIdBarang2.Text = ""
                'C.TBarang.Text = ""
                Tp2.Text = "0"
                Tl2.Text = "0"
                Tt2.Text = "0"
                Tj2.Text = "0"
                TidBahan.Text = ""
                CBahan.Text = ""
                TFinishing.Text = ""
            Case "Edit"
                GGVM_conn()
                If TBarang2.Text = "" Then
                    MsgBox("Isi Dulu Barang-Nya .. !!", MsgBoxStyle.Information, "Pemberitahuan")
                    Exit Sub
                ElseIf CPrinting.Checked = False Then
                    MsgBox("Pilih Salah satu Printing / Cutting .. !!", MsgBoxStyle.Information, "Pemberitahuan")
                    Exit Sub
                ElseIf TIdBarang2.Text = "" Then
                    Dim kd As String

                    sql = ""
                    sql = sql & " select * from barang_int where barang = '" & TBarang2.Text & "' "
                    cmd = New OdbcCommand(sql, conn)
                    dr = cmd.ExecuteReader
                    dr.Read()
                    If Not dr.HasRows Then
                        'Count Kode Barang
                        s = ""
                        s = s & " Select max(idbarang_int)As id from barang"
                        cmd = New OdbcCommand(s, conn)
                        dr = cmd.ExecuteReader
                        dr.Read()
                        kd = "000000" + dr.GetString(0)
                        kd = Microsoft.VisualBasic.Right(kd, 6)

                        c = ""
                        c = c & "insert barang (idsubkel,kdbarang,barang_int,keterangan_brgint)"
                        c = c & "values ('79', '" & kd & "' , '" & TBarang2.Text & "', 'Otomatis') "
                        cmd = New OdbcCommand(c, conn)
                        cmd.ExecuteNonQuery()

                        c = ""
                        c = c & " Select max(idbarang_int) As id from barang "
                        da = New OdbcDataAdapter(c, conn)
                        dt = New DataTable
                        da.Fill(dt)
                        If dt.Rows.Count > 0 Then
                            TIdBarang2.Text = dt.Rows(0)("id")
                        End If
                    Else
                        MsgBox("BARANG SUDAH ADA .. !!", MsgBoxStyle.Information, "Pemberitahuan")
                        Exit Sub
                    End If

                End If
                c = ""
                c = c & " update prd_detail_po_printing set "
                c = c & " idbarang = '" & TIdBarang2.Text & "',"
                c = c & " panjang_prt = '" & Tp2.Text & "', "
                c = c & " tinggi_prt = '" & Tt2.Text & "', "
                c = c & " lebar_prt = '" & Tl2.Text & "', "
                c = c & " qty_prt = '" & Tj2.Text & "' , "
                c = c & " idbahan = '" & TidBahan.Text & "' , "
                c = c & " idfinishing = '" & TidFinishing.Text & "' "
                c = c & " where iddetail_po_prt = '" & TidDetailPoPrt.Text & "'"
                cmd = New OdbcCommand(c, conn)
                cmd.ExecuteNonQuery()
                Me.Cursor = Cursors.Default

                MsgBox("Data PO sudah di-Update !!..", MsgBoxStyle.Information, "Information")
                GGVM_conn_close()
                Panel2.Visible = False
                PanelAlasan.Visible = False
                TAlasan.Text = ""
                TampilDetailPrinting()
                Proses = "Entry"
                tutupdesain()


        End Select
    End Sub
    Private Sub KirimPrinting_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles KirimPrinting.ItemClick
        
    End Sub

    Private Sub BtnAccDsn_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BtnAccDsn.ItemClick
        If TidPoDsn.Text = "" Then
            MsgBox("Tidak ada data yang akan di Entry, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
            Exit Sub
        End If
        GGVM_conn()
        If BtnAccDsn.Caption = "TERIMA PO" Then
            BtnAccDsn.DropDownEnabled = False
            c = ""
            c = c & " update po_desain set "
            c = c & "terima_po_dsn = now() "
            c = c & " where idpo_dsn = '" & ListPODsn.Items(brspo).SubItems(6).Text & "'"
            cmd = New OdbcCommand(c, conn)
            cmd.ExecuteNonQuery()

            c = ""
            c = c & " insert prd_history_dataorder (iddtorder,idstatusproyek,waktu,userid) values "
            c = c & " ('" & ListPODsn.Items(brspo).SubItems(8).Text & "','21',now(),'" & userid & "')"
            cmd = New OdbcCommand(c, conn)
            cmd.ExecuteNonQuery()

            MsgBox("PO Telah di Terima !!..", MsgBoxStyle.Information, "Information")
            ListDetailPODsn.Enabled = True
            BtnEntryDsn.Enabled = True
            If BtnAccDsn.Caption = "KIRIM PO" Then
                BtnAccDsn.Enabled = True
                BtnAccDsn.DropDownEnabled = True
            Else
                BtnAccDsn.Enabled = False
            End If
            RbTerima.Checked = False
            RbKirim.Checked = True
        ElseIf BtnAccDsn.Caption = "KIRIM PO" Then
            Dim ada As Boolean
            Dim jmldt As Integer
            ada = False
            jmldt = 0
            For i = 0 To ListDetailPODsn.Items.Count - 1
                If ListDetailPODsn.Items(i).Checked = True Then
                    ada = True
                End If
            Next
            If ada = False Then
                MsgBox("Tidak ada data yang akan di Entry, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
                ListDetailPODsn.Focus()
                Exit Sub
            End If
            GGVM_conn()
            ListDetailPODsn.BeginUpdate()
            s = ""
            s = s & " select idpe from proyek"
            s = s & " where iddtorder ='" & ListPODsn.Items(brspo).SubItems(8).Text & "'"
            da = New OdbcDataAdapter(s, conn)
            'ds.Clear()
            dt = New DataTable
            dt.Clear()
            da.Fill(dt)

            If dt.Rows.Count > 0 Then
                TidPE.Text = dt.Rows(0)("idpe")
            End If


            sql = ""
            sql = sql & "insert into po_printing (idpe,"
            sql = sql & " tanggal_prt ) values "
            sql = sql & " ('" & TidPE.Text & "', now())"
            cmd = New OdbcCommand(sql, conn)
            cmd.ExecuteNonQuery()


            sql = ""
            sql = sql & " select max(idpo_prt)as idprt from po_printing"
            da = New OdbcDataAdapter(sql, conn)
            'ds.Clear()
            Dim tblid_prt = New DataTable
            tblid_prt.Clear()
            da.Fill(tblid_prt)
            If ListDetailPODsn.CheckedIndices.Count > 0 Then
                For i = 0 To ListDetailPODsn.CheckedIndices.Count - 1
                    'c = ""
                    'c = c & " update prd_dataorder set"
                    'c = c & " idstatus_proyek ='21'"
                    'c = c & " where iddtorder = '" & iddtorder & "'"
                    'cmd = New OdbcCommand(c, conn)
                    'cmd.ExecuteNonQuery()


                    sql = "select iddetail_po_dsn from prd_trans_detailpo_desain where iddetail_po_dsn = '" & ListDetailPODsn.Items(ListDetailPODsn.CheckedIndices(i)).SubItems(13).Text & "' "
                    cmd = New OdbcCommand(sql, conn)
                    dr = cmd.ExecuteReader
                    dr.Read()
                    If Not dr.HasRows Then
                        Dim sql1 = "insert into prd_trans_detailpo_desain (iddetail_po_dsn,idtoko,idbarang, idpo_prt, time_kirim_prt) values (?,?,?,?,?) "
                        cmd = New OdbcCommand
                        With cmd
                            .CommandText = (sql1)
                            .Parameters.Add("@iddetail_po_dsn", OdbcType.BigInt).Value = Convert.ToInt32(ListDetailPODsn.Items(ListDetailPODsn.CheckedIndices(i)).SubItems(13).Text)
                            .Parameters.Add("@idtoko", OdbcType.Int).Value = Convert.ToInt32(ListDetailPODsn.Items(ListDetailPODsn.CheckedIndices(i)).SubItems(11).Text)
                            .Parameters.Add("@idbarang", OdbcType.Int).Value = Convert.ToInt32(ListDetailPODsn.Items(ListDetailPODsn.CheckedIndices(i)).SubItems(9).Text)
                            .Parameters.Add("@idpo_prt", OdbcType.Int).Value = Convert.ToInt32(tblid_prt.Rows(0)("idprt"))
                            .Parameters.Add("@time_kirim_prt", OdbcType.DateTime).Value = Now()
                            .Connection = conn
                        End With
                        dr = cmd.ExecuteReader
                        Console.WriteLine(cmd.CommandText.ToString)
                        While dr.Read
                            Console.WriteLine(dr(0))
                            Console.WriteLine()
                        End While
                        Console.ReadLine()
                    Else
                        Dim sql1 = "update prd_trans_detailpo_desain set time_kirim_prt = now(), idpo_prt ='" & tblid_prt.Rows(0)("idprt") & "' where iddetail_po_dsn ='" & ListDetailPODsn.Items(ListDetailPODsn.CheckedIndices(i)).SubItems(13).Text & "'  "
                        cmd = New OdbcCommand(sql1, conn)
                        cmd.ExecuteNonQuery()
                    End If
                Next
                c = ""
                c = c & " update prd_detail_po_printing set"
                c = c & " idpo_prt ='" & tblid_prt.Rows(0)("idprt") & "'"
                c = c & " where idpo_prt is null"
                cmd = New OdbcCommand(c, conn)
                cmd.ExecuteNonQuery()
                MsgBox("PO Telah di Kirim ke Printing !!..", MsgBoxStyle.Information, "Information")
            End If
            For Each item As ListViewItem In ListDetailPODsn.Items
                sql = ""
                sql = sql & "select * from prd_trans_detailpo_desain where idbarang = '" & item.SubItems(9).Text & "'"
                cmd = New OdbcCommand(sql, conn)
                dr = cmd.ExecuteReader
                dr.Read()
                If Not dr.HasRows Then
                    ' MsgBox("Harap Kirim dulu Semua PO, Sebelum Menyelesaikan ", MsgBoxStyle.Information)
                    Exit Sub
                Else
                    c = ""
                    c = c & " update po_desain set time_closhing_dsn = now(),kirim_po_dsn = now()"
                    c = c & " where idpo_dsn ='" & ListPODsn.Items(brspo).SubItems(6).Text & "'"
                    cmd = New OdbcCommand(c, conn)
                    cmd.ExecuteNonQuery()

                    s = ""
                    s = s & " update po_produksi set selesai_desain = now()"
                    s = s & " where idpo_prd ='" & ListPODsn.Items(brspo).SubItems(5).Text & "'"
                    cmd = New OdbcCommand(s, conn)
                    cmd.ExecuteNonQuery()
                End If
                MsgBox("PO SUDAH DISELESAIKAN !!", MsgBoxStyle.Information)
            Next


            ListDetailPODsn.EndUpdate()
            'Insert History Kirim PO Cutting
            sql = ""
            sql = sql & " insert prd_history_dataorder (iddtorder,idstatusproyek,waktu,userid) values "
            sql = sql & " ('" & ListPODsn.Items(brspo).SubItems(8).Text & "','22',now(),'" & userid & "')"
            cmd = New OdbcCommand(sql, conn)
            cmd.ExecuteNonQuery()

            TampilDetailPrinting()
            TampilPODeTAIL()
        Else
            Return
        End If
        SqlDataSource1.FillAsync()
        BtnAccDsn.Enabled = False

    End Sub

    Private Sub BtnSelesai_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BtnSelesai.ItemClick
        GGVM_conn()
        Dim ada As Boolean
        Dim jmldt As Integer
        ada = False
        jmldt = 0
        For i = 0 To ListDetailPODsn.Items.Count - 1
            If ListDetailPODsn.Items(i).Checked = True Then
                ada = True
            End If
        Next
        If ada = False Then
            MsgBox("Tidak ada data yang akan di Selesaikan, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
            ListDetailPODsn.Focus()
            Exit Sub
        End If
        For Each item As ListViewItem In ListDetailPODsn.Items
           
            sql = ""
            sql = sql & "select * from prd_trans_detailpo_desain where idbarang = '" & item.SubItems(9).Text & "'"
            cmd = New OdbcCommand(sql, conn)
            dr = cmd.ExecuteReader
            dr.Read()
            If Not dr.HasRows Then
                MsgBox("Harap Kirim dulu Semua PO, Sebelum Menyelesaikan ", MsgBoxStyle.Information)
                Exit Sub
            Else
                c = ""
                c = c & " update po_desain set time_closhing_dsn = now(),kirim_po = now()"
                c = c & " where idpo_dsn ='" & ListPODsn.Items(brspo).SubItems(6).Text & "'"
                cmd = New OdbcCommand(c, conn)
                cmd.ExecuteNonQuery()

                s = ""
                s = s & " update po_produksi set selesai_desain = now()"
                s = s & " where idpo_prd ='" & ListPODsn.Items(brspo).SubItems(5).Text & "'"
                cmd = New OdbcCommand(s, conn)
                cmd.ExecuteNonQuery()
            End If
        Next
        MsgBox("PO SUDAH DISELESAIKAN !!", MsgBoxStyle.Information)
        SqlDataSource1.FillAsync()
        'GGVM_conn_close()
    End Sub
    Private Sub ListDetailPODsn_DrawColumnHeader(sender As Object, e As DrawListViewColumnHeaderEventArgs)
        e.DrawDefault = True
    End Sub

    Private Sub ListDetailPODsn_DrawSubItem(sender As Object, e As DrawListViewSubItemEventArgs)
        'Using txtbrsh As New SolidBrush(e.SubItem.ForeColor)
        '    If ListDetailPODsn.SelectedIndices.Contains(e.ItemIndex) And ListDetailPODsn.Focused Then
        '        e.Graphics.FillRectangle(New SolidBrush(Color.FromKnownColor(KnownColor.Highlight)), e.Bounds)
        '        txtbrsh.Color = Color.White
        '    End If
        '    Using sf As New StringFormat With {.Alignment = StringAlignment.Near, .LineAlignment = StringAlignment.Center, .FormatFlags = StringFormatFlags.NoWrap, .Trimming = StringTrimming.EllipsisCharacter}
        '        If e.Item.SubItems(1) Is e.SubItem Then
        '            e.DrawDefault = False
        '            Dim rb As New Rectangle(e.Bounds.X + e.Bounds.Height, e.Bounds.Y, e.Bounds.Width + e.Bounds.Height, e.Bounds.Height)
        '            If e.Item.SubItems(15).Text <> "" And e.Item.SubItems(16).Text = "" Then
        '                e.Graphics.DrawImage(My.Resources.message_prt, e.Bounds.X, e.Bounds.Y, e.Bounds.Height, e.Bounds.Height)
        '            ElseIf e.Item.SubItems(16).Text <> "" And e.Item.SubItems(15).Text = "" Then
        '                e.Graphics.DrawImage(My.Resources.message_cut, e.Bounds.X, e.Bounds.Y, e.Bounds.Height, e.Bounds.Height)
        '            ElseIf e.Item.SubItems(15).Text <> "" And e.Item.SubItems(16).Text <> "" Then
        '                e.Graphics.DrawImage(My.Resources.message, e.Bounds.X, e.Bounds.Y, e.Bounds.Height, e.Bounds.Height)
        '            ElseIf e.Item.SubItems(17).Text = "Y" Then
        '                e.Graphics.DrawImage(My.Resources._sub, e.Bounds.X, e.Bounds.Y, e.Bounds.Height, e.Bounds.Height)
        '            End If
        '            e.Graphics.DrawString(e.SubItem.Text, e.SubItem.Font, txtbrsh, rb, sf)
        '        Else
        '            e.DrawDefault = True
        '        End If
        '    End Using
        'End Using
    End Sub
    Private Sub BtnEditDsn_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BtnEditDsn.ItemClick
        Dim ada, item As Boolean
        Dim jmldt, jmldetail, brs, brs2 As Integer
        ada = False
        item = False
        jmldt = 0
        jmldetail = 0
        For i = 0 To ListDetailPODsn.Items.Count - 1
            If ListDetailPODsn.Items(i).Checked = True Then
                ada = True
                brs = i
                jmldt = jmldt + 1
            End If
        Next
        If ada = False Then
            MsgBox("Tidak ada data yang akan dipilih, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
            ListDetailPODsn.Focus()
            Exit Sub
        ElseIf jmldt > 1 Then
            MsgBox("Hanya 1(satu) data PO-DESIGN yg bisa di-Entry !!...", MsgBoxStyle.Information, "Information")
            Exit Sub
        End If

        For g = 0 To ListPOPrint.Items.Count - 1
            If ListPOPrint.Items(g).Checked = True Then
                item = True
                brs2 = g
                jmldetail = jmldetail + 1
            End If
        Next



        AutoCompBarangPrinting()
        For i = 0 To ListDetailPODsn.Items.Count - 1
            If ListDetailPODsn.Items(i).Checked = True Then
                brs = i
                TToko.Text = ListDetailPODsn.Items(i).SubItems(0).Text
                TKota.Text = ListDetailPODsn.Items(i).SubItems(1).Text
                TBarang1.Text = ListDetailPODsn.Items(i).SubItems(2).Text
                TBrand.Text = ListDetailPODsn.Items(i).SubItems(3).Text
                Tp1.Text = ListDetailPODsn.Items(i).SubItems(4).Text
                Tl1.Text = ListDetailPODsn.Items(i).SubItems(5).Text
                Tt1.Text = ListDetailPODsn.Items(i).SubItems(6).Text
                Tj1.Text = ListDetailPODsn.Items(i).SubItems(8).Text
                TIdBarang1.Text = ListDetailPODsn.Items(i).SubItems(9).Text
                TidPO.Text = ListDetailPODsn.Items(i).SubItems(10).Text
                TIdToko.Text = ListDetailPODsn.Items(i).SubItems(11).Text
                TKeterangan.Text = ListDetailPODsn.Items(i).SubItems(14).Text
            End If
        Next

        If item = False Then
             MsgBox("Tidak ada data PO Printing yang akan dipilih, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
            ListPOPrint.Focus()
        ElseIf item = True Then
            For i = 0 To ListPOPrint.Items.Count - 1
                If ListPOPrint.Items(i).Checked = True Then
                    CPrinting.Checked = True
                    brs2 = i
                    TBarang2.Text = ListPOPrint.Items(i).SubItems(1).Text
                    Tp2.Text = ListPOPrint.Items(i).SubItems(2).Text
                    Tl2.Text = ListPOPrint.Items(i).SubItems(3).Text
                    Tt2.Text = ListPOPrint.Items(i).SubItems(4).Text
                    Tj2.Text = ListPOPrint.Items(i).SubItems(5).Text
                    TidDetailPoPrt.Text = ListPOPrint.Items(i).SubItems(7).Text
                    CBahan.Text = ListPOPrint.Items(i).SubItems(9).Text
                    TFinishing.Text = ListPOPrint.Items(i).SubItems(10).Text
                    TidBahan.Text = ListPOPrint.Items(i).SubItems(11).Text
                    TidFinishing.Text = ListPOPrint.Items(i).SubItems(12).Text
                    TidPoPrt.Text = ListPOPrint.Items(i).SubItems(13).Text

                End If
            Next
        ElseIf jmldetail > 1 Then
            MsgBox("Hanya 1(satu) data PO-PRINTING yg bisa di-Entry !!...", MsgBoxStyle.Information, "Information")
            Exit Sub
        End If
        EntryMode()
        Panel2.Visible = True
        Proses = "Edit"
    End Sub

    Private Sub ListDetailPODsn_SelectedIndexChanged(sender As Object, e As EventArgs)
        Me.Cursor = Cursors.WaitCursor
        With Me.ListDetailPODsn
            'For Each check As ListViewItem In ListDetailPODsn.CheckedItems
            '    check.Checked = False
            'Next
            For Each item As ListViewItem In ListDetailPODsn.SelectedItems
                item.Checked = True
                brske = item.Index
            Next
            TIdToko.Text = ListDetailPODsn.Items(brske).SubItems(11).Text
            'TIdBarang1.Text = ListDetailPODsn.Items(brske).SubItems(11).Text
        End With
        TampilDetailPrinting()
        Me.Cursor = Cursors.Default
    End Sub
    Private Sub CBahan_SelectedValueChanged(sender As Object, e As EventArgs) Handles CBahan.SelectedValueChanged
        GGVM_conn()
        s = "select idbahan from prd_bahan_printing where bahan= '" & CBahan.Text & "'"
        cmd = New OdbcCommand(s, conn)
        dr = cmd.ExecuteReader
        dr.Read()
        If Not dr.HasRows Then
            TidBahan.Text = ""
        Else
            TidBahan.Text = dr.Item("idbahan")
        End If
        GGVM_conn_close()
    End Sub
    Private Panel1Captured As Boolean
    Private Panel1Grabbed As Point

    Private Sub Panel1_MouseDown(ByVal sender As Object, ByVal e As System.Windows.Forms.MouseEventArgs) Handles Panel2.MouseDown
        Panel1Captured = True
        Panel1Grabbed = e.Location
    End Sub

    Private Sub Panel1_MouseMove(ByVal sender As Object, ByVal e As System.Windows.Forms.MouseEventArgs) Handles Panel2.MouseMove
        If (Panel1Captured) Then Panel2.Location = Panel2.Location + e.Location - Panel1Grabbed
    End Sub

    Private Sub Panel1_MouseUp(ByVal sender As Object, ByVal e As System.Windows.Forms.MouseEventArgs) Handles Panel2.MouseUp
        Panel1Captured = False
    End Sub
    Private Sub ListPODsn_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ListPODsn.SelectedIndexChanged
        Me.Cursor = Cursors.WaitCursor

        TampilPODeTAIL()
        With Me.ListPODsn
            For Each check As ListViewItem In ListPODsn.CheckedItems
                TidPO.Text = ""
                TidPoDsn.Text = ""
                check.Checked = False
            Next
            For Each item As ListViewItem In ListPODsn.SelectedItems
                'item.Checked = True
                brspo = item.Index
                'TidPO.Text = ListPODsn.Items(brspo).SubItems(5).Text
                TidPoDsn.Text = ListPODsn.Items(brspo).SubItems(6).Text
                item.Checked = True
                Dim tbl As New DataTable
                GGVM_conn()
                s = ""
                s = s & " select if (terima_po_dsn is null,'', terima_po_dsn)as acc from po_desain"
                s = s & " where idpo_dsn='" & TidPoDsn.Text & "'"
                da = New OdbcDataAdapter(s, conn)
                'ds.Clear()
                tbl = New DataTable
                tbl.Clear()
                da.Fill(tbl)

                If tbl.Rows(0)("acc") = "" Then
                    ' MsgBox("Data Belum di Acc tidak dapat di Entry!!...", MsgBoxStyle.Information, "Information")
                    ListDetailPODsn.Enabled = False
                    BtnAccDsn.Enabled = True
                    BtnEntryDsn.Enabled = False
                    RbTerima.Checked = True
                    RbKirim.Checked = False
                Else
                    ListDetailPODsn.Enabled = True
                    BtnEntryDsn.Enabled = True
                    If BtnAccDsn.Caption = "KIRIM PO" Then
                        BtnAccDsn.Enabled = True
                    Else
                        BtnAccDsn.Enabled = False
                    End If
                    RbTerima.Checked = False
                    RbKirim.Checked = True
                End If
            Next

            'TextBox1.Text = ListPODsn.Items(brspo).SubItems(8).Text
            'tiddtorder.text = ListPODsn.Items(brske).SubItems(9).Text
        End With


        Me.Cursor = Cursors.Default
        TampilPODeTAIL()
        ' GGVM_conn_close()
    End Sub

    Private Sub ListDetailPODsn_SelectedIndexChanged_1(sender As Object, e As EventArgs) Handles ListDetailPODsn.SelectedIndexChanged
        Me.Cursor = Cursors.WaitCursor
        With Me.ListDetailPODsn
            'For Each check As ListViewItem In ListDetailPODsn.CheckedItems
            '    check.Checked = False
            'Next
            For Each item As ListViewItem In ListDetailPODsn.SelectedItems
                item.Checked = True
                brske = item.Index
            Next
            TIdToko.Text = ListDetailPODsn.Items(brske).SubItems(11).Text
            TidDetailDsn.Text = ListDetailPODsn.Items(brske).SubItems(13).Text
        End With
        TampilDetailPrinting()
        Me.Cursor = Cursors.Default
    End Sub

    Private Sub FilterPekerjaan_CheckedChanged(sender As Object, e As EventArgs) Handles FilterPekerjaan.CheckedChanged
        If FilterPekerjaan.Checked = True Then
            CbOnprogress.Checked = False
            Call TampilPODesain()
        Else
            Call TampilPODesain()
        End If
    End Sub

    Private Sub CbOnprogress_CheckedChanged(sender As Object, e As EventArgs) Handles CbOnprogress.CheckedChanged
        If CbOnprogress.Checked = True Then
            FilterPekerjaan.Checked = False
            BtnSelesai.Enabled = True
            Call TampilPODesain()
        Else
            Call TampilPODesain()
            BtnSelesai.Enabled = False
        End If
    End Sub

    Private Sub BtnRefreshDsn_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BtnRefreshDsn.ItemClick
        ListPODsn.Items.Clear()
        ListDetailPODsn.Items.Clear()
        TampilPODesain()
    End Sub
End Class
