Imports DevExpress.XtraGrid.Views.Base
Imports DevExpress.XtraGrid.Views.Grid
Imports DevExpress.XtraGrid.Columns
Imports System.Data.Odbc

Public Class POInternalDesign
    Dim s, c As String
    Dim idpo, idpodsn, iddtorder As String
    Dim filter As Boolean
    Dim brske, brspo As Integer
    Dim LoadDT As String
    Dim Proses As String
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill the SqlDataSource asynchronously
        SqlDataSource1.FillAsync()
    End Sub

#Region " Deklarasi  Listview"
    Private Sub ListHeadDetail()
        ListDetailPODsn.FullRowSelect = True
        ListDetailPODsn.MultiSelect = True
        ListDetailPODsn.View = View.Details
        ListDetailPODsn.OwnerDraw = True
        ListDetailPODsn.CheckBoxes = True
        'ListDetailPODsn.SmallImageList = ImgList
        ListDetailPODsn.Columns.Clear()
        ListDetailPODsn.Items.Clear()
        ListDetailPODsn.Columns.Add("TOKO", 180, HorizontalAlignment.Left)
        ListDetailPODsn.Columns.Add("KOTA", 120, HorizontalAlignment.Left)
        ListDetailPODsn.Columns.Add("BARANG", 200, HorizontalAlignment.Left)
        ListDetailPODsn.Columns.Add("BRAND", 100, HorizontalAlignment.Left)
        ListDetailPODsn.Columns.Add("P", 60, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("L", 60, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("T", 60, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("SISI", 60, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("JML", 60, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("IDBARANG", 0, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("IDPOPRD", 0, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("IDTOKO", 0, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("IDBRAND", 0, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("IDDTORDER", 0, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("IDDETAILDSN", 0, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("KETERANGAN", 150, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("time_kirim_prt", 0, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("time_kirim_cut", 0, HorizontalAlignment.Right)
        ListDetailPODsn.Columns.Add("issubkon", 0, HorizontalAlignment.Right)
    End Sub

    Private Sub ListHeadPrint()
        ListPOPrint.FullRowSelect = True
        ListPOPrint.MultiSelect = True
        ListPOPrint.View = View.Details
        ListPOPrint.CheckBoxes = True
        ListPOPrint.Columns.Clear()
        ListPOPrint.Items.Clear()
        ListPOPrint.Columns.Add("TOKO", 180, HorizontalAlignment.Left)
        ListPOPrint.Columns.Add("BARANG", 200, HorizontalAlignment.Left)
        ListPOPrint.Columns.Add("P", 60, HorizontalAlignment.Right)
        ListPOPrint.Columns.Add("L", 60, HorizontalAlignment.Right)
        ListPOPrint.Columns.Add("T", 60, HorizontalAlignment.Right)
        ListPOPrint.Columns.Add("SISI", 60, HorizontalAlignment.Right)
        ListPOPrint.Columns.Add("JML", 60, HorizontalAlignment.Right)
        ListPOPrint.Columns.Add("iditem_prt", 0, HorizontalAlignment.Right)
        ListPOPrint.Columns.Add("iddetail_po_prt", 0, HorizontalAlignment.Right)
        ListPOPrint.Columns.Add("idtoko", 0, HorizontalAlignment.Right)
        ListPOPrint.Columns.Add("BAHAN", 110, HorizontalAlignment.Right)
        ListPOPrint.Columns.Add("FINISHING", 150, HorizontalAlignment.Right)
    End Sub
#End Region
#Region "Deklarasi Fungsi"
    Private Sub TampilPODeTAIL()

        Dim s As String
        Dim i As Integer
        Dim tbl As New DataTable

        ListDetailPODsn.Items.Clear()
        ListPOPrint.Items.Clear()
        GGVM_conn()
        s = ""
        s = s & " SELECT * from view_detailpo_dsn"
        s = s & " WHERE idpo_prd ='" & idpo & "' "
        If filter = True Then
            s = s & " and kirim_po is not null and kirim_ppic is not null"
        Else
            s = s & " and kirim_po is null and kirim_ppic is null"
        End If

        ' s = s & " WHERE idpo_prd ='" & TidPO.Text & "'"
        da = New OdbcDataAdapter(s, conn)
        'ds.Clear()
        tbl = New DataTable
        tbl.Clear()
        da.Fill(tbl)
        For i = 0 To tbl.Rows.Count - 1
            With ListDetailPODsn
                .Items.Add(tbl.Rows(i)("toko"))
                With .Items(.Items.Count - 1).SubItems
                    .Add(tbl.Rows(i)("kota"))
                    .Add(tbl.Rows(i)("barang"))
                    .Add(tbl.Rows(i)("brand"))
                    .Add(Int(Val(tbl.Rows(i)("panjang_prd"))))
                    .Add(Int(Val(tbl.Rows(i)("lebar_prd"))))
                    .Add(Int(Val(tbl.Rows(i)("tinggi_prd"))))
                    .Add(Int(Val(tbl.Rows(i)("sisi_prd"))))
                    .Add(Int(Val(tbl.Rows(i)("qty_prd"))))
                    .Add(tbl.Rows(i)("idbarang"))
                    .Add(tbl.Rows(i)("idpo_prd"))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("idtoko")), "", tbl.Rows(i)("idtoko")))
                    .Add(tbl.Rows(i)("idbrand"))
                    .Add(tbl.Rows(i)("iddtorder"))
                    .Add(tbl.Rows(i)("iddetail_dsn"))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("keterangan")), "", tbl.Rows(i)("keterangan")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("time_kirim_prt")), "", tbl.Rows(i)("time_kirim_prt")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("time_kirim_cut")), "", tbl.Rows(i)("time_kirim_cut")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("issubkon")), "", tbl.Rows(i)("issubkon")))
                End With
            End With
        Next
        GGVM_conn_close()
    End Sub
    Private Sub TampilDetailPrinting()
        Dim s As String
        Dim i As Integer
        Dim tbl As New DataTable

        ListPOPrint.Items.Clear()
        GGVM_conn()
        s = ""
        s = s & " select * from view_detailPoPrint "
        s = s & " where idtoko = '" & TIdToko.Text & "' and iddetail_dsn='" & ListDetailPODsn.Items(brske).SubItems(14).Text & "' "
        da = New OdbcDataAdapter(s, conn)
        'ds.Clear()
        tbl = New DataTable
        tbl.Clear()
        da.Fill(tbl)
        For i = 0 To tbl.Rows.Count - 1
            With ListPOPrint
                .Items.Add(tbl.Rows(i)("toko"))
                With .Items(.Items.Count - 1).SubItems
                    .Add(tbl.Rows(i)("item_prt"))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("panjang_prt")), "", tbl.Rows(i)("panjang_prt")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("lebar_prt")), "", tbl.Rows(i)("lebar_prt")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("tinggi_prt")), "", tbl.Rows(i)("tinggi_prt")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("sisi_prt")), "", tbl.Rows(i)("sisi_prt")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("qty_prt")), "", tbl.Rows(i)("qty_prt")))
                    .Add(tbl.Rows(i)("iditem_prt"))
                    .Add(tbl.Rows(i)("iddetail_po_prt"))
                    If tbl.Rows(i)("idtoko") Is DBNull.Value Then
                        .Add("0")
                    Else
                        .Add(tbl.Rows(i)("idtoko"))
                    End If
                    .Add(IIf(IsDBNull(tbl.Rows(i)("bahan")), "", tbl.Rows(i)("bahan")))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("finishing")), "", tbl.Rows(i)("finishing")))
                    .Add(tbl.Rows(i)("idbahan"))
                    .Add(tbl.Rows(i)("idfinishing"))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("idpo_prt")), "", tbl.Rows(i)("idpo_prt")))
                End With
            End With
        Next
        GGVM_conn_close()
    End Sub

   
    Private Sub AutoCompBarangPrinting()

        Try
            GGVM_conn()
            s = ""
            s = s & " select * from ("
            s = s & " select barang,idbarang from barang"
            s = s & " where idsubkel = 79"
            s = s & " and status='1'"
            's = s & " and barang like '%" & TBarang2.Text & "%'"
            s = s & " group by barang ) y"
            da = New OdbcDataAdapter(s, conn)
            ds = New DataSet
            da.Fill(ds)
            Dim BarangPrinting As New AutoCompleteStringCollection
            For i As Integer = 0 To ds.Tables(0).Rows.Count - 1
                BarangPrinting.Add(ds.Tables(0).Rows(i)("barang"))
            Next
            With TBarang2
                .AutoCompleteSource = AutoCompleteSource.CustomSource
                .AutoCompleteCustomSource = BarangPrinting
                .AutoCompleteMode = AutoCompleteMode.Suggest
            End With
        Catch ex As Exception
            MsgBox("Terjadi kesalahan! " & ex.Message)
        End Try
        GGVM_conn_close()
    End Sub
    Private Sub AutoCompFinishing()
        Try
            GGVM_conn()
            s = ""
            s = s & " select finishing from prd_finishing_printing "
            s = s & " where status='1'"
            da = New OdbcDataAdapter(s, conn)
            ds = New DataSet
            da.Fill(ds)
            Dim FinishingItem As New AutoCompleteStringCollection
            For i As Integer = 0 To ds.Tables(0).Rows.Count - 1
                FinishingItem.Add(ds.Tables(0).Rows(i)("finishing"))
            Next
            With TFinishing
                .AutoCompleteSource = AutoCompleteSource.CustomSource
                .AutoCompleteCustomSource = FinishingItem
                .AutoCompleteMode = AutoCompleteMode.Suggest
            End With
        Catch ex As Exception
            MsgBox("Terjadi kesalahan! " & ex.Message)
        End Try
        GGVM_conn_close()
    End Sub
    Private Sub EntryMode()
        TToko.Enabled = False
        TBarang1.Enabled = False
        TBrand.Enabled = False
        Tp1.Enabled = False
        Tl1.Enabled = False
        Tt1.Enabled = False

        TBarang2.Enabled = True
        Tp2.Enabled = True
        Tl2.Enabled = True
        Tt2.Enabled = True
        CCutting.Enabled = True
        CPrinting.Enabled = True
        BtnSimpanDetail.Enabled = True
        BtnSimpanDetail.Text = "Simpan"
        ListPOPrint.Enabled = False
        BtnEditDsn.Enabled = False
        BtnEntryDsn.Enabled = False
    End Sub
    Private Sub LoadBahan()
        Dim s As String
        CBahan.Items.Clear()
        GGVM_conn()
        s = ""
        s = s & "select bahan from prd_bahan_printing"
        da = New OdbcDataAdapter(s, conn)
        'ds.Clear()
        dt = New DataTable
        dt.Clear()
        da.Fill(dt)

        For i = 0 To dt.Rows.Count - 1
            With CBahan
                .Items.Add(dt.Rows(i)("bahan"))
            End With
        Next
        GGVM_conn_close()
    End Sub
    Private Sub tutupdesain()
        TToko.Text = ""
        TBarang1.Text = ""
        TBrand.Text = ""
        Tp1.Text = ""
        Tl1.Text = ""
        Tt1.Text = ""
        Tj1.Text = ""
        TIdBarang1.Text = ""
        TIdpoprd.Text = ""
        TIdToko.Text = ""
        TIdBrand.Text = ""
        TBarang2.Text = ""
        TIdBarang2.Text = ""
        'C.TBarang.Text = ""
        Tp2.Text = "0"
        Tl2.Text = "0"
        Tt2.Text = "0"
        Tj2.Text = "0"
        Tp3.Text = "0"
        Tl3.Text = "0"
        Tt3.Text = "0"
        Tp3.Text = "0"
        TidBahan.Text = ""
        CBahan.Text = ""
        TFinishing.Text = ""
        CCutting.Enabled = False
        CPrinting.Enabled = False
        ListPOPrint.Enabled = True
        BtnEditDsn.Enabled = False
        BtnEntryDsn.Enabled = True
    End Sub
#End Region
    Private Sub POInternalDesign_Load(sender As Object, e As EventArgs) Handles Me.Load
        ' ...
        ListHeadDetail()
        ListHeadPrint()
        RbTerima.Checked = True
        BtnAccDsn.Caption = "TERIMA PO"
    End Sub


    Private Sub RbTerima_CheckedChanged(sender As Object, e As EventArgs) Handles RbTerima.CheckedChanged
        If RbTerima.Checked = True Then
            BtnAccDsn.Enabled = True
            BtnAccDsn.Caption = "TERIMA PO"
            BtnAccDsn.DropDownEnabled = False
            RbKirim.Checked = False
            Dim view As ColumnView = GridPODsn
            Dim colterimapo As GridColumn = view.Columns("terima_po")
            colterimapo.ClearFilter()
            colterimapo.FilterInfo = New DevExpress.XtraGrid.Columns.ColumnFilterInfo("[terima_po] IS NULL")
            BtnSelesai.Enabled = False
            SqlDataSource1.FillAsync()
        Else
            Dim view As ColumnView = GridPODsn
            Dim colterimapo As GridColumn = view.Columns("terima_po")
            colterimapo.ClearFilter()
        End If
    End Sub

    Private Sub RbKirim_CheckedChanged(sender As Object, e As EventArgs) Handles RbKirim.CheckedChanged
        If RbKirim.Checked = True Then
            RbTerima.Checked = False
            BtnAccDsn.Enabled = True
            BtnAccDsn.Caption = "KIRIM PO"
            BtnAccDsn.DropDownEnabled = True
            BtnSelesai.Enabled = True
            Dim view As ColumnView = GridPODsn
            Dim colterimapo As GridColumn = view.Columns("terima_po")
            Dim closing As GridColumn = view.Columns("time_closhing")
            colterimapo.ClearFilter()
            closing.ClearFilter()
            closing.FilterInfo = New DevExpress.XtraGrid.Columns.ColumnFilterInfo("[time_closhing] IS NULL")
            colterimapo.FilterInfo = New DevExpress.XtraGrid.Columns.ColumnFilterInfo("[terima_po] IS NOT NULL")
            SqlDataSource1.FillAsync()
        Else
            Dim view As ColumnView = GridPODsn
            Dim colterimapo As GridColumn = view.Columns("terima_po")
            Dim closing As GridColumn = view.Columns("time_closhing")
            colterimapo.ClearFilter()
            closing.ClearFilter()
        End If
    End Sub

    Private Sub GroupControl3_CustomButtonChecked(sender As Object, e As DevExpress.XtraBars.Docking2010.BaseButtonEventArgs) Handles GroupControl3.CustomButtonChecked
        RbKirim.Checked = False
        RbTerima.Checked = False
        Dim view As ColumnView = GridPODsn
        Dim closing As GridColumn = view.Columns("time_closhing")
        closing.ClearFilter()
        closing.FilterInfo = New DevExpress.XtraGrid.Columns.ColumnFilterInfo("[time_closhing] IS NOT NULL")
        
    End Sub

    Private Sub GroupControl3_CustomButtonUnchecked(sender As Object, e As DevExpress.XtraBars.Docking2010.BaseButtonEventArgs) Handles GroupControl3.CustomButtonUnchecked
        Dim view As ColumnView = GridPODsn
        Dim closing As GridColumn = view.Columns("time_closhing")
        closing.ClearFilter()
        RbKirim.Checked = True
    End Sub
    Private Sub TFinishing_TextChanged(sender As Object, e As EventArgs) Handles TFinishing.TextChanged
        Try
            GGVM_conn()
            s = " select * from prd_finishing_printing where finishing =  '" & TFinishing.Text & "' and status='1'"
            cmd = New OdbcCommand(s, conn)
            dr = cmd.ExecuteReader
            dr.Read()
            If Not dr.HasRows Then
                TidFinishing.Text = ""
            Else
                TidFinishing.Text = dr.Item("idfinishing")
            End If
        Catch ex As Exception
            MsgBox("Terjadi kesalahan! " & ex.Message)
        End Try
        GGVM_conn_close()
    End Sub
    Private Sub TBarang2_TextChanged(sender As Object, e As EventArgs) Handles TBarang2.TextChanged
        Try
            GGVM_conn()
            s = " select * from barang where barang =  '" & TBarang2.Text & "' and status='1'"
            cmd = New OdbcCommand(s, conn)
            dr = cmd.ExecuteReader
            dr.Read()
            If Not dr.HasRows Then
                TIdBarang2.Text = ""
            Else
                TIdBarang2.Text = dr.Item("idbarang")
            End If
        Catch ex As Exception
            MsgBox("Terjadi kesalahan! " & ex.Message)
        End Try
        GGVM_conn_close()
    End Sub
    Private Sub BtnEntryDsn_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BtnEntryDsn.ItemClick
        Dim ada, item As Boolean
        Dim jmldt, jmldetail, brs2 As Integer
        ada = False
        item = False
        jmldt = 0
        If idpo = "" Then
            MsgBox("Tidak ada data PO yang akan di Entry, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
            Exit Sub
        End If
        If idpodsn = "" Then
            MsgBox("Tidak ada data Detail yang akan dipilih, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
            Exit Sub
        End If
        For i = 0 To ListDetailPODsn.Items.Count - 1
            If ListDetailPODsn.Items(i).Checked = True Then
                item = True
                brs2 = i
                jmldetail = jmldetail + 1
            End If
        Next
        If item = False Then
            MsgBox("Tidak ada data yang akan dipilih, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
            ListDetailPODsn.Focus()
            Exit Sub
        End If
        If jmldetail > 1 Then
            MsgBox("Hanya 1(satu) data PO-DESAIN yg bisa di-Entry !!...", MsgBoxStyle.Information, "Information")
            Exit Sub
        End If
        'Panel1.Visible = True
        AutoCompBarangPrinting()

        AutoCompFinishing()
        For i = 0 To ListDetailPODsn.Items.Count - 1
            If ListDetailPODsn.Items(i).Checked = True Then
                brs2 = i
                TToko.Text = ListDetailPODsn.Items(i).SubItems(0).Text
                TKota.Text = ListDetailPODsn.Items(i).SubItems(1).Text
                TBarang1.Text = ListDetailPODsn.Items(i).SubItems(2).Text
                TBrand.Text = ListDetailPODsn.Items(i).SubItems(3).Text
                Tp1.Text = ListDetailPODsn.Items(i).SubItems(4).Text
                Tl1.Text = ListDetailPODsn.Items(i).SubItems(5).Text
                Tt1.Text = ListDetailPODsn.Items(i).SubItems(6).Text
                Tj1.Text = ListDetailPODsn.Items(i).SubItems(8).Text
                TIdBarang1.Text = ListDetailPODsn.Items(i).SubItems(9).Text
                TIdpoprd.Text = ListDetailPODsn.Items(i).SubItems(10).Text
                TIdToko.Text = ListDetailPODsn.Items(i).SubItems(11).Text
                TIdBrand.Text = ListDetailPODsn.Items(i).SubItems(12).Text
                TKeterangan.Text = ListDetailPODsn.Items(i).SubItems(15).Text
                'CBarang.Checked = False
                TBarang2.Text = ""
                'C.TBarang.Text = ""
                Tp2.Text = Val(Tp1.Text) + 5
                Tl2.Text = Val(Tl1.Text) + 5
                Tt2.Text = Val(Tt1.Text) + 5
                Tj2.Text = Val(Tj1.Text) + 5
                LoadBahan()
            End If
        Next
        Panel2.Visible = True
        EntryMode()
        Proses = "Entry"
    End Sub
    

    Private Sub GridControl1_Click(sender As Object, e As EventArgs) Handles GridControl1.Click

    End Sub

    Private Sub GridPODsn_RowClick(sender As Object, e As RowClickEventArgs) Handles GridPODsn.RowClick
        idpo = ""
        idpodsn = ""
        iddtorder = ""
        idpo = GridPODsn.GetRowCellValue(GridPODsn.FocusedRowHandle, "idpo_dsn").ToString()
        idpodsn = GridPODsn.GetRowCellValue(GridPODsn.FocusedRowHandle, "idpo_dsn").ToString()
        iddtorder = GridPODsn.GetRowCellValue(GridPODsn.FocusedRowHandle, "iddtorder").ToString()
    End Sub

    Private Sub GridPODsn_SelectionChanged(sender As Object, e As DevExpress.Data.SelectionChangedEventArgs) Handles GridPODsn.SelectionChanged
        idpo = ""
        idpodsn = ""
        iddtorder = ""
        idpo = GridPODsn.GetRowCellValue(GridPODsn.FocusedRowHandle, "idpo_prd").ToString()
        idpodsn = GridPODsn.GetRowCellValue(GridPODsn.FocusedRowHandle, "idpo_dsn").ToString()
        iddtorder = GridPODsn.GetRowCellValue(GridPODsn.FocusedRowHandle, "iddtorder").ToString()
        GGVM_conn()
        s = ""
        s = s & " select if (terima_po is null,'', terima_po)as acc from po_desain"
        s = s & " where idpo_dsn='" & idpodsn & "'"
        da = New OdbcDataAdapter(s, conn)
        'ds.Clear()
        dt = New DataTable
        dt.Clear()
        da.Fill(dt)

        If dt.Rows(0)("acc") = "" Then
            ' MsgBox("Data Belum di Acc tidak dapat di Entry!!...", MsgBoxStyle.Information, "Information")
            ListDetailPODsn.Enabled = False
            BtnAccDsn.Enabled = True
            BtnEntryDsn.Enabled = False
            RbTerima.Checked = True
            RbKirim.Checked = False
        Else
            ListDetailPODsn.Enabled = True
            BtnEntryDsn.Enabled = True
            If BtnAccDsn.Caption = "KIRIM PO" Then
                BtnAccDsn.Enabled = True
            Else
                BtnAccDsn.Enabled = False
            End If
            RbTerima.Checked = False
            RbKirim.Checked = True
        End If
        TampilPODeTAIL()
    End Sub

    Private Sub BtnExitDsn_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BtnExitDsn.ItemClick
        If BtnExitDsn.Caption = "HAPUS" Then
            If MsgBox("Apakah anda yakin untuk menghapus detail Printing ?..", MsgBoxStyle.YesNo, "Question") = MsgBoxResult.Yes Then
                s = ""
                s = s & " update prd_detail_printing set isdelete='Y' "
                s = s & " where iddetail_po_prt ='" & TidDetailPoPrt.Text & "'"
                cmd = New OdbcCommand(s, conn)
                cmd.ExecuteNonQuery()
                BtnExitDsn.Caption = "KELUAR"
                TampilDetailPrinting()
            Else
                BtnExitDsn.Caption = "KELUAR"
            End If
        Else
            Me.Dispose()
        End If
    End Sub

    Private Sub BtnCetakPO_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BtnCetakPO.ItemClick
        If idpo = "" Then
            MsgBox("Tidak ada data PO-INTERNAL yg dicetak, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
            Exit Sub
        End If

        Me.Cursor = Cursors.WaitCursor


        Dim report As New XtraReport
        'report = New ReportPOInternalDesain
        ' Obtain a parameter and set its value.
        'report.Parameters("idpo_dsn").Value = idpo

        ' Hide the Parameters' UI from end-users (if you did not hide it at design time).
        'report.Parameters("idpe").Visible = False

        Me.Cursor = Cursors.Default
        ' report.ShowPreview()
    End Sub
    Private Sub CCutting_CheckedChanged(sender As Object, e As EventArgs) Handles CCutting.CheckedChanged
        If CCutting.Checked = True Then
            PanelC.Visible = True
        Else
            PanelC.Visible = False
            Tt3.Text = "0"
            Tl3.Text = "0"
            Tp3.Text = "0"
            Tj3.Text = "0"
        End If
    End Sub
    Private Sub CPrinting_CheckedChanged(sender As Object, e As EventArgs) Handles CPrinting.CheckedChanged
        If CPrinting.Checked = True Then
            PanelP.Visible = True
        Else
            PanelP.Visible = False
            Tt2.Text = "0"
            Tl2.Text = "0"
            Tp2.Text = "0"
            Tj2.Text = "0"
        End If
    End Sub
    Private Sub TidDetailPoPrt_TextChanged(sender As Object, e As EventArgs) Handles TidDetailPoPrt.TextChanged
        Try
            GGVM_conn()
            s = " select * from view_detailpoprint where iddetail_po_prt =  '" & TidDetailPoPrt.Text & "' and idpo_prt is null"
            cmd = New OdbcCommand(s, conn)
            dr = cmd.ExecuteReader
            dr.Read()
            If Not dr.HasRows Then
                Tp2.Text = ""
                Tt2.Text = ""
                Tl2.Text = ""
                Tj2.Text = ""
                TBarang2.Text = ""
                ' TIdBarang2.Text = ""
            Else
                Tp2.Text = dr.Item("panjang_prt")
                Tt2.Text = dr.Item("tinggi_prt")
                Tl2.Text = dr.Item("lebar_prt")
                Tj2.Text = dr.Item("qty_prt")
                TBarang2.Text = dr.Item("item_prd")
                'TIdBarang2.Text = dr.Item("iditem_prd")
            End If
        Catch ex As Exception
            MsgBox("Terjadi kesalahan! " & ex.Message)
        End Try
        GGVM_conn_close()
    End Sub
    Private Sub ListPOPrint_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ListPOPrint.SelectedIndexChanged
        Me.Cursor = Cursors.WaitCursor
        With Me.ListPOPrint
            For Each check As ListViewItem In ListPOPrint.CheckedItems
                check.Checked = False
            Next
            For Each item As ListViewItem In ListPOPrint.SelectedItems
                item.Checked = True
                brske = item.Index
            Next
            TidDetailPoPrt.Text = ListPOPrint.Items(brske).SubItems(9).Text
            BtnExitDsn.Caption = "HAPUS"
            BtnEditDsn.Enabled = True
        End With
        'TampilDetailPrinting()
        Me.Cursor = Cursors.Default
    End Sub


    Private Sub BtnSimpanAlasan_Click(sender As Object, e As EventArgs) Handles BtnSimpanAlasan.Click
        If Len(Me.TAlasan.Text) < 10 Or Len(Me.TAlasan.Text) > 150 Then
            MsgBox("Alasan Terlalu Pendek, Minimal 10 Huruf !", MsgBoxStyle.Information, "Information !!")
            Exit Sub
        Else
            GGVM_conn()

        End If
        If CPrinting.Checked = True Then
            c = ""
            c = c & " update po_printing set "
            c = c & " user_edit = '" & userid & "',"
            c = c & " timeedit = now()"
            c = c & " where idpo_prt = '" & TidPoPrt.Text & "'"
            cmd = New OdbcCommand(c, conn)
            cmd.ExecuteNonQuery()

            sql = ""
            sql = sql & "insert into prd_revisi_detail_po_printing (iddetail_po_prt,idpo_prt,idtoko,iditem_prt,item_prt,idsatuan,keterangan,panjang_prd, "
            sql = sql & " tinggi_prd,lebar_prd,sisi_prd,qty_prd,panjang_prt,tinggi_prt,lebar_prt,sisi_prt,qty_prt,idfinishing,idbahan,iddetail_dsn, "
            sql = sql & " isdelete,time_start,time_end,time_temp,done)  select * from prd_detail_po_printing WHERE iddetail_po_prt =  '" & TidDetailPoPrt.Text & "'"
            cmd = New OdbcCommand(sql, conn)
            cmd.ExecuteNonQuery()

            c = ""
            c = c & " insert into prd_revisi_po_printing (iddetail_po_prt,alasan,timerevisi,userrevisi) "
            c = c & " values ('" & TidDetailPoPrt.Text & "', '" & TAlasan.Text & "', now(),'" & userid & "' ) "
            cmd = New OdbcCommand(c, conn)
            cmd.ExecuteNonQuery()

            s = ""
            s = s & " select max(idrevisi) as id from prd_revisi_po_printing where iddetail_po_prt ='" & TidDetailPoPrt.Text & "'"
            da = New OdbcDataAdapter(s, conn)
            dt = New DataTable
            dt.Clear()
            da.Fill(dt)
            idrevisi.Text = dt.Rows(0)("id")

            sql = ""
            sql = sql & " update prd_revisi_detail_po_printing set idrevisi = '" & idrevisi.Text & "' "
            sql = sql & " where iddetail_po_prt = '" & TidDetailPoPrt.Text & "' and idrevisi is null "
            cmd = New OdbcCommand(sql, conn)
            cmd.ExecuteNonQuery()


            sql = ""
            sql = sql & " select max(revisike)as idrev  from prd_revisi_po_printing where iddetail_po_prt = '" & TidDetailPoPrt.Text & "'"
            da = New OdbcDataAdapter(sql, conn)
            dt = New DataTable
            dt.Clear()
            da.Fill(dt)
            Dim count As Integer
            If dt.Rows(0)("idrev") = "1" Then
                count = 1
            Else
                count = 0
            End If
            count = dt.Rows(0)("idrev") + 1

            c = ""
            c = c & "update prd_revisi_po_printing set revisike ='" & count & "' where idrevisi ='" & idrevisi.Text & "'"
            cmd = New OdbcCommand(c, conn)
            cmd.ExecuteNonQuery()

            c = ""
            c = c & " update prd_detail_po_printing set "
            c = c & " iditem_prt = '" & TIdBarang2.Text & "',"
            c = c & " item_prt = '" & TBarang2.Text & "', "
            c = c & " panjang_prd = '" & Tp1.Text & "', "
            c = c & " tinggi_prd = '" & Tt1.Text & "', "
            c = c & " lebar_prd = '" & Tl1.Text & "', "
            c = c & " qty_prd = '" & Tj1.Text & "', "
            c = c & " panjang_prt = '" & Tp2.Text & "', "
            c = c & " tinggi_prt = '" & Tt2.Text & "', "
            c = c & " lebar_prt = '" & Tl2.Text & "', "
            c = c & " qty_prt = '" & Tj2.Text & "' , "
            c = c & " idbahan = '" & TidBahan.Text & "' , "
            c = c & " idfinishing = '" & TidFinishing.Text & "' "
            c = c & " where iddetail_po_prt = '" & TidDetailPoPrt.Text & "'"
            cmd = New OdbcCommand(c, conn)
            cmd.ExecuteNonQuery()
            Me.Cursor = Cursors.Default
        End If
        If CCutting.Checked = True Then
            c = ""
            c = c & " update po_cutting set "
            c = c & " user_edit = '" & userid & "',"
            c = c & " timeedit = now()"
            c = c & " where idpo_cut = '" & TidPOCut.Text & "'"
            cmd = New OdbcCommand(c, conn)
            cmd.ExecuteNonQuery()

            sql = ""
            sql = sql & "insert into prd_revisi_detail_po_cutting (iddetail_po_prt,idpo_prt,idtoko,iditem_prt,item_prt,idsatuan,keterangan,panjang_prd, "
            sql = sql & " tinggi_prd,lebar_prd,sisi_prd,qty_prd,panjang_cut,tinggi_cut,lebar_cut,sisi_cut,qty_cut,idfinishing,idbahan,iddetail_dsn, "
            sql = sql & " isdelete,time_start,time_end,time_temp,done)  select * from prd_detail_po_cutting WHERE iddetail_po_cut =  '" & TidDetailpoCut.Text & "'"
            cmd = New OdbcCommand(sql, conn)
            cmd.ExecuteNonQuery()

            c = ""
            c = c & " insert into prd_revisi_po_cutting (iddetail_po_prt,alasan,timerevisi,userrevisi) "
            c = c & " values ('" & TidDetailpoCut.Text & "', '" & TAlasan.Text & "', now(),'" & userid & "' ) "
            cmd = New OdbcCommand(c, conn)
            cmd.ExecuteNonQuery()


            s = ""
            s = s & " select max(idrevisi) as id from prd_revisi_po_cutting where iddetail_po_cut ='" & TidDetailpoCut.Text & "'"
            da = New OdbcDataAdapter(s, conn)
            dt = New DataTable
            dt.Clear()
            da.Fill(dt)
            idrevisi.Text = dt.Rows(0)("id")

            sql = ""
            sql = sql & " update prd_revisi_detail_po_cutting set idrevisi = '" & idrevisi.Text & "' "
            sql = sql & " where iddetail_po_cut = '" & TidDetailpoCut.Text & "' and idrevisi is null "
            cmd = New OdbcCommand(sql, conn)
            cmd.ExecuteNonQuery()

            sql = ""
            sql = sql & " select max(revisike)as idrev  from prd_revisi_po_cutting where iddetail_po_cut = '" & TidDetailPoPrt.Text & "'"
            da = New OdbcDataAdapter(sql, conn)
            dt = New DataTable
            dt.Clear()
            da.Fill(dt)
            Dim count As Integer
            If dt.Rows(0)("idrev") = "1" Then
                count = 1
            Else
                count = 0
            End If
            count = dt.Rows(0)("idrev") + 1


            c = ""
            c = c & "update prd_revisi_po_cutting set revisike ='" & count & "' where idrevisi ='" & idrevisi.Text & "'"
            cmd = New OdbcCommand(c, conn)
            cmd.ExecuteNonQuery()

            c = ""
            c = c & " update prd_detail_po_cutting set "
            c = c & " iditem_cut = '" & TIdBarang2.Text & "',"
            c = c & " item_cut = '" & TBarang2.Text & "', "
            c = c & " panjang_prd = '" & Tp1.Text & "', "
            c = c & " tinggi_prd = '" & Tt1.Text & "', "
            c = c & " lebar_prd = '" & Tl1.Text & "', "
            c = c & " qty_prd = '" & Tj1.Text & "', "
            c = c & " panjang_cut = '" & Tp3.Text & "', "
            c = c & " tinggi_cut = '" & Tt3.Text & "', "
            c = c & " lebar_cut = '" & Tl3.Text & "', "
            c = c & " qty_cut = '" & Tj3.Text & "' , "
            c = c & " idbahan = '" & TidBahan.Text & "' , "
            c = c & " idfinishing = '" & TidFinishing.Text & "' "
            c = c & " where iddetail_po_cut = '" & TidDetailpoCut.Text & "'"
            cmd = New OdbcCommand(c, conn)
            cmd.ExecuteNonQuery()
            Me.Cursor = Cursors.Default
        End If

        MsgBox("Data PO sudah di-Update !!..", MsgBoxStyle.Information, "Information")
        GGVM_conn_close()
        Panel2.Visible = False
        PanelAlasan.Visible = False
        TAlasan.Text = ""
        TampilDetailPrinting()
        Proses = "Entry"
        tutupdesain()
    End Sub

    Private Sub BtnClose_Click(sender As Object, e As EventArgs) Handles BtnClose.Click
        Panel2.Visible = False

        tutupdesain()
    End Sub

    Private Sub BtnSimpanDetail_Click(sender As Object, e As EventArgs) Handles BtnSimpanDetail.Click
        Select Case Proses
            Case "Entry"
                GGVM_conn()
                If TBarang2.Text = "" Then
                    MsgBox("Isi Dulu Barang-Nya .. !!", MsgBoxStyle.Information, "Pemberitahuan")
                    Exit Sub
                ElseIf CPrinting.Checked = False And CCutting.Checked = False Then
                    MsgBox("Pilih Salah satu Printing / Cutting .. !!", MsgBoxStyle.Information, "Pemberitahuan")
                    Exit Sub
                ElseIf TidBahan.Text = "" Then
                    MsgBox("Bahan Tidak ada , Harap diisi dulu .. !! ", MsgBoxStyle.OkOnly, "Pemberitahuan")
                    Exit Sub
                ElseIf TIdBarang2.Text = "" Then
                    Dim kd As String

                    sql = ""
                    sql = sql & " select * from barang where barang = '" & TBarang2.Text & "' "
                    cmd = New OdbcCommand(sql, conn)
                    dr = cmd.ExecuteReader
                    dr.Read()
                    If Not dr.HasRows Then
                        'Count Kode Barang
                        s = ""
                        s = s & " Select max(idbarang)As id from barang"
                        cmd = New OdbcCommand(s, conn)
                        dr = cmd.ExecuteReader
                        dr.Read()
                        kd = "000000" + dr.GetString(0)
                        kd = Microsoft.VisualBasic.Right(kd, 6)

                        c = ""
                        c = c & "insert barang (idsubkel,kdbarang,barang,keterangan)"
                        c = c & "values ('79', '" & kd & "' , '" & TBarang2.Text & "', 'Otomatis') "
                        cmd = New OdbcCommand(c, conn)
                        cmd.ExecuteNonQuery()

                        c = ""
                        c = c & " Select max(idbarang) As id from barang "
                        da = New OdbcDataAdapter(c, conn)
                        dt = New DataTable
                        da.Fill(dt)
                        If dt.Rows.Count > 0 Then
                            TIdBarang2.Text = dt.Rows(0)("id")
                        End If
                    Else
                        MsgBox("BARANG SUDAH ADA .. !!", MsgBoxStyle.Information, "Pemberitahuan")
                        Exit Sub
                    End If
                ElseIf TidFinishing.Text = "" Then
                    s = ""
                    s = s & " insert into prd_finishing_printing ( finishing, status ) values ('" & TFinishing.Text & "', '1')"
                    cmd = New OdbcCommand(s, conn)
                    cmd.ExecuteNonQuery()

                    c = ""
                    c = c & " Select max(idfinishing) As id from prd_finishing_printing "
                    da = New OdbcDataAdapter(c, conn)
                    dt = New DataTable
                    da.Fill(dt)
                    If dt.Rows.Count > 0 Then
                        TidFinishing.Text = dt.Rows(0)("id")
                    End If
                ElseIf TidBahan.Text = "" Then
                    s = ""
                    s = s & " insert into prd_bahan_printing ( bahan, status ) values ('" & CBahan.Text & "', '1')"
                    cmd = New OdbcCommand(s, conn)
                    cmd.ExecuteNonQuery()

                    c = ""
                    c = c & " Select max(idbahan) As id from prd_bahan_printing "
                    da = New OdbcDataAdapter(c, conn)
                    dt = New DataTable
                    da.Fill(dt)
                    If dt.Rows.Count > 0 Then
                        TidBahan.Text = dt.Rows(0)("id")
                    End If
                End If
                If CPrinting.Checked = True Then
                    c = ""
                    c = c & " insert into prd_detail_po_printing (idtoko,iditem_prt,item_prt,idsatuan,panjang_prd,tinggi_prd,lebar_prd,"
                    c = c & "  qty_prd,panjang_prt,tinggi_prt,lebar_prt, "
                    If CMal.Checked = True Then
                        c = c & " keterangan, "
                    End If
                    c = c & " qty_prt,iddetail_dsn,idfinishing,idbahan) values "
                    c = c & " ('" & TIdToko.Text & "','" & TIdBarang2.Text & "','" & TBarang2.Text & "','1','" & Tp1.Text & "',"
                    c = c & "'" & Tt1.Text & "','" & Tl1.Text & "','" & Tj1.Text & "','" & Tp2.Text & "','" & Tt2.Text & "','" & Tl2.Text & "', "
                    If CMal.Checked = True Then
                        c = c & " 'MAL', "
                    End If
                    c = c & " '" & Tj2.Text & "','" & ListDetailPODsn.Items(brske).SubItems(14).Text & "','" & TidFinishing.Text & "','" & TidBahan.Text & "')"
                    cmd = New OdbcCommand(c, conn)
                    cmd.ExecuteNonQuery()
                    Me.Cursor = Cursors.Default
                End If
                If CCutting.Checked = True Then
                    c = ""
                    c = c & " insert into prd_detail_po_cutting (idtoko,iditem_cut,item_cut,idsatuan,panjang_prd,tinggi_prd,lebar_prd,"
                    c = c & "  qty_prd,panjang_cut,tinggi_cut,lebar_cut, "
                    If CMal.Checked = True Then
                        c = c & " keterangan, "
                    End If
                    c = c & " qty_cut,iddetail_dsn,idfinishing,idbahan) values "
                    c = c & " ('" & TIdToko.Text & "','" & TIdBarang2.Text & "','" & TBarang2.Text & "','1','" & Tp1.Text & "',"
                    c = c & "'" & Tt1.Text & "','" & Tl1.Text & "','" & Tj1.Text & "','" & Tp3.Text & "','" & Tt3.Text & "','" & Tl3.Text & "', "
                    If CMal.Checked = True Then
                        c = c & " 'MAL', "
                    End If
                    c = c & " '" & Tj3.Text & "','" & ListDetailPODsn.Items(brske).SubItems(14).Text & "','" & TidFinishing.Text & "','" & TidBahan.Text & "')"
                    cmd = New OdbcCommand(c, conn)
                    cmd.ExecuteNonQuery()
                    Me.Cursor = Cursors.Default
                End If
                If CSubKerjaan.Checked = True Then
                    sql = ""
                    sql = sql & "insert into prd_trans_detailpo_desain (iddetail_po_dsn,idtoko,idbarang,issubkon) "
                    sql = sql & " values ('" & ListDetailPODsn.Items(brske).SubItems(14).Text & "','" & TIdToko.Text & "','" & TIdBarang1.Text & "','Y') "
                    cmd = New OdbcCommand(sql, conn)
                    cmd.ExecuteNonQuery()
                End If

                MsgBox("Data PO sudah di-SIMPAN !!..", MsgBoxStyle.Information, "Information")
                GGVM_conn_close()
                'Panel1.Visible = False
                TampilDetailPrinting()
                TBarang2.Text = ""
                TIdBarang2.Text = ""
                'C.TBarang.Text = ""
                Tp2.Text = "0"
                Tl2.Text = "0"
                Tt2.Text = "0"
                Tj2.Text = "0"
                Tp3.Text = "0"
                Tl3.Text = "0"
                Tt3.Text = "0"
                Tp3.Text = "0"
                TidBahan.Text = ""
                CBahan.Text = ""
                TFinishing.Text = ""
            Case "Edit"
                GGVM_conn()
                If TBarang2.Text = "" Then
                    MsgBox("Isi Dulu Barang-Nya .. !!", MsgBoxStyle.Information, "Pemberitahuan")
                    Exit Sub
                ElseIf CPrinting.Checked = False And CCutting.Checked = False Then
                    MsgBox("Pilih Salah satu Printing / Cutting .. !!", MsgBoxStyle.Information, "Pemberitahuan")
                    Exit Sub
                ElseIf TIdBarang2.Text = "" Then
                    Dim kd As String

                    sql = ""
                    sql = sql & " select * from barang where barang = '" & TBarang2.Text & "' "
                    cmd = New OdbcCommand(sql, conn)
                    dr = cmd.ExecuteReader
                    dr.Read()
                    If Not dr.HasRows Then
                        'Count Kode Barang
                        s = ""
                        s = s & " Select max(idbarang)As id from barang"
                        cmd = New OdbcCommand(s, conn)
                        dr = cmd.ExecuteReader
                        dr.Read()
                        kd = "000000" + dr.GetString(0)
                        kd = Microsoft.VisualBasic.Right(kd, 6)

                        c = ""
                        c = c & "insert barang (idsubkel,kdbarang,barang,keterangan)"
                        c = c & "values ('79', '" & kd & "' , '" & TBarang2.Text & "', 'Otomatis') "
                        cmd = New OdbcCommand(c, conn)
                        cmd.ExecuteNonQuery()

                        c = ""
                        c = c & " Select max(idbarang) As id from barang "
                        da = New OdbcDataAdapter(c, conn)
                        dt = New DataTable
                        da.Fill(dt)
                        If dt.Rows.Count > 0 Then
                            TIdBarang2.Text = dt.Rows(0)("id")
                        End If
                    Else
                        MsgBox("BARANG SUDAH ADA .. !!", MsgBoxStyle.Information, "Pemberitahuan")
                        Exit Sub
                    End If

                End If
                PanelAlasan.Visible = True
                TAlasan.Text = ""
                TAlasan.Focus()


        End Select
    End Sub
    Private Sub KirimCutting_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles KirimCutting.ItemClick
        ListDetailPODsn.BeginUpdate()
        If ListDetailPODsn.CheckedIndices.Count > 0 Then
            For i = 0 To ListDetailPODsn.CheckedIndices.Count - 1
                'c = ""
                'c = c & " update prd_dataorder set"
                'c = c & " idstatus_proyek ='29'"
                'c = c & " where iddtorder = '" & ListDetailPODsn.Items(brske).SubItems(13).Text & "'"
                'cmd = New OdbcCommand(c, conn)
                'cmd.ExecuteNonQuery()


                s = ""
                s = s & " select idpe from proyek"
                s = s & " where iddtorder ='" & ListDetailPODsn.Items(brske).SubItems(13).Text & "'"
                da = New OdbcDataAdapter(s, conn)
                'ds.Clear()
                dt = New DataTable
                dt.Clear()
                da.Fill(dt)

                If dt.Rows.Count > 0 Then
                    TidPE.Text = dt.Rows(0)("idpe")
                End If


                sql = ""
                sql = sql & "insert into po_cutting (iddtorder,"
                If TidPE.Text <> "" Then
                    sql = sql & "idpe ,"
                End If
                sql = sql & " tanggal,iddivisi,idstatus_proyek ) values "
                sql = sql & " ('" & iddtorder & "',"
                If TidPE.Text <> "" Then
                    sql = sql & " '" & TidPE.Text & "', "
                End If
                sql = sql & " now(),'9','29')"
                cmd = New OdbcCommand(sql, conn)
                cmd.ExecuteNonQuery()

                sql = ""
                sql = sql & " select max(idpo_cut)as idcut from po_cutting"
                da = New OdbcDataAdapter(sql, conn)
                'ds.Clear()
                Dim tblid_cut = New DataTable
                tblid_cut.Clear()
                da.Fill(tblid_cut)

                c = ""
                c = c & " update prd_detail_po_cutting set"
                c = c & " idpo_cut ='" & tblid_cut.Rows(0)("idcut") & "'"
                c = c & " where idpo_cut is null"
                cmd = New OdbcCommand(c, conn)
                cmd.ExecuteNonQuery()

                sql = "select iddetail_po_dsn from prd_trans_detailpo_desain where iddetail_po_dsn = '" & ListDetailPODsn.Items(ListDetailPODsn.CheckedIndices(i)).SubItems(13).Text & "' "
                cmd = New OdbcCommand(sql, conn)
                dr = cmd.ExecuteReader
                dr.Read()
                If Not dr.HasRows Then
                    Dim sql1 = "insert into prd_trans_detailpo_desain (iddetail_po_dsn,idtoko,idbarang, idpo_cut, time_kirim_cut) values (?,?,?,?,?) "
                    cmd = New OdbcCommand
                    With cmd
                        .CommandText = (sql1)
                        .Parameters.Add("@iddetail_po_dsn", OdbcType.BigInt).Value = Convert.ToInt32(ListDetailPODsn.Items(ListDetailPODsn.CheckedIndices(i)).SubItems(13).Text)
                        .Parameters.Add("@idtoko", OdbcType.Int).Value = Convert.ToInt32(ListDetailPODsn.Items(ListDetailPODsn.CheckedIndices(i)).SubItems(10).Text)
                        .Parameters.Add("@idbarang", OdbcType.Int).Value = Convert.ToInt32(ListDetailPODsn.Items(ListDetailPODsn.CheckedIndices(i)).SubItems(8).Text)
                        .Parameters.Add("@idpo_cut", OdbcType.Int).Value = Convert.ToInt32(tblid_cut.Rows(0)("idcut"))
                        .Parameters.Add("@time_kirim", OdbcType.DateTime).Value = Now()
                        .Connection = conn
                    End With
                    dr = cmd.ExecuteReader
                    Console.WriteLine(cmd.CommandText.ToString)
                    While dr.Read
                        Console.WriteLine(dr(0))
                        Console.WriteLine()
                    End While
                    Console.ReadLine()
                Else
                    Dim sql1 = "update prd_trans_detailpo_desain set time_kirim_cut = now(), idpo_cut ='" & tblid_cut.Rows(0)("idcut") & "' where iddetail_po_dsn ='" & ListDetailPODsn.Items(ListDetailPODsn.CheckedIndices(i)).SubItems(13).Text & "'  "
                    cmd = New OdbcCommand(sql1, conn)
                    cmd.ExecuteNonQuery()
                End If


            Next
        End If
        ListDetailPODsn.EndUpdate()

        MsgBox("PO Telah di Kirim ke Cutting !!..", MsgBoxStyle.Information, "Information")
        'Insert History Kirim PO Cutting
        sql = ""
        sql = sql & " insert prd_history_dataorder (iddtorder,idstatusproyek,waktu,userid) values "
        sql = sql & " ('" & ListDetailPODsn.Items(brske).SubItems(13).Text & "','30',now(),'" & userid & "')"
        cmd = New OdbcCommand(sql, conn)
        cmd.ExecuteNonQuery()

        TampilDetailPrinting()
        TampilPODeTAIL()
    End Sub

    Private Sub KirimPrinting_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles KirimPrinting.ItemClick
        Dim ada As Boolean
        Dim jmldt As Integer
        ada = False
        jmldt = 0
        For i = 0 To ListDetailPODsn.Items.Count - 1
            If ListDetailPODsn.Items(i).Checked = True Then
                ada = True
            End If
        Next
        If ada = False Then
            MsgBox("Tidak ada data yang akan di Entry, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
            ListDetailPODsn.Focus()
            Exit Sub
        End If
        GGVM_conn()
        ListDetailPODsn.BeginUpdate()
        If ListDetailPODsn.CheckedIndices.Count > 0 Then
            For i = 0 To ListDetailPODsn.CheckedIndices.Count - 1
                'c = ""
                'c = c & " update prd_dataorder set"
                'c = c & " idstatus_proyek ='21'"
                'c = c & " where iddtorder = '" & iddtorder & "'"
                'cmd = New OdbcCommand(c, conn)
                'cmd.ExecuteNonQuery()


                s = ""
                s = s & " select idpe from proyek"
                s = s & " where iddtorder ='" & iddtorder & "'"
                da = New OdbcDataAdapter(s, conn)
                'ds.Clear()
                dt = New DataTable
                dt.Clear()
                da.Fill(dt)

                If dt.Rows.Count > 0 Then
                    TidPE.Text = dt.Rows(0)("idpe")
                End If


                sql = ""
                sql = sql & "insert into po_printing (iddtorder,"
                If TidPE.Text <> "" Then
                    sql = sql & "idpe ,"
                End If
                sql = sql & " tanggal,iddivisi,idstatus_proyek ) values "
                sql = sql & " ('" & iddtorder & "',"
                If TidPE.Text <> "" Then
                    sql = sql & " '" & TidPE.Text & "', "
                End If
                sql = sql & " now(),'9','21')"
                cmd = New OdbcCommand(sql, conn)
                cmd.ExecuteNonQuery()


                sql = ""
                sql = sql & " select max(idpo_prt)as idprt from po_printing"
                da = New OdbcDataAdapter(sql, conn)
                'ds.Clear()
                Dim tblid_prt = New DataTable
                tblid_prt.Clear()
                da.Fill(tblid_prt)

                c = ""
                c = c & " update prd_detail_po_printing set"
                c = c & " idpo_prt ='" & tblid_prt.Rows(0)("idprt") & "'"
                c = c & " where idpo_prt is null"
                cmd = New OdbcCommand(c, conn)
                cmd.ExecuteNonQuery()

                sql = "select iddetail_po_dsn from prd_trans_detailpo_desain where iddetail_po_dsn = '" & ListDetailPODsn.Items(ListDetailPODsn.CheckedIndices(i)).SubItems(13).Text & "' "
                cmd = New OdbcCommand(sql, conn)
                dr = cmd.ExecuteReader
                dr.Read()
                If Not dr.HasRows Then
                    Dim sql1 = "insert into prd_trans_detailpo_desain (iddetail_po_dsn,idtoko,idbarang, idpo_prt, time_kirim_prt) values (?,?,?,?,?) "
                    cmd = New OdbcCommand
                    With cmd
                        .CommandText = (sql1)
                        .Parameters.Add("@iddetail_po_dsn", OdbcType.BigInt).Value = Convert.ToInt32(ListDetailPODsn.Items(ListDetailPODsn.CheckedIndices(i)).SubItems(13).Text)
                        .Parameters.Add("@idtoko", OdbcType.Int).Value = Convert.ToInt32(ListDetailPODsn.Items(ListDetailPODsn.CheckedIndices(i)).SubItems(10).Text)
                        .Parameters.Add("@idbarang", OdbcType.Int).Value = Convert.ToInt32(ListDetailPODsn.Items(ListDetailPODsn.CheckedIndices(i)).SubItems(8).Text)
                        .Parameters.Add("@idpo_prt", OdbcType.Int).Value = Convert.ToInt32(tblid_prt.Rows(0)("idprt"))
                        .Parameters.Add("@time_kirim_prt", OdbcType.DateTime).Value = Now()
                        .Connection = conn
                    End With
                    dr = cmd.ExecuteReader
                    Console.WriteLine(cmd.CommandText.ToString)
                    While dr.Read
                        Console.WriteLine(dr(0))
                        Console.WriteLine()
                    End While
                    Console.ReadLine()
                Else
                    Dim sql1 = "update prd_trans_detailpo_desain set time_kirim_prt = now(), idpo_prt ='" & tblid_prt.Rows(0)("idprt") & "' where iddetail_po_dsn ='" & ListDetailPODsn.Items(ListDetailPODsn.CheckedIndices(i)).SubItems(13).Text & "'  "
                    cmd = New OdbcCommand(sql1, conn)
                    cmd.ExecuteNonQuery()
                End If


            Next
        End If
        ListDetailPODsn.EndUpdate()

        MsgBox("PO Telah di Kirim ke Printing !!..", MsgBoxStyle.Information, "Information")
        'Insert History Kirim PO Cutting
        sql = ""
        sql = sql & " insert prd_history_dataorder (iddtorder,idstatusproyek,waktu,userid) values "
        sql = sql & " ('" & idpo & "','22',now(),'" & userid & "')"
        cmd = New OdbcCommand(sql, conn)
        cmd.ExecuteNonQuery()

        TampilDetailPrinting()
        TampilPODeTAIL()
    End Sub

    Private Sub BtnAccDsn_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BtnAccDsn.ItemClick
        If idpodsn = "" Then
            MsgBox("Tidak ada data yang akan di Entry, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
            Exit Sub
        End If
        GGVM_conn()
        If BtnAccDsn.Caption = "TERIMA PO" Then
            BtnAccDsn.DropDownEnabled = False
            c = ""
            c = c & " update po_desain set "
            c = c & "terima_po = now() "
            c = c & " where idpo_dsn = '" & idpodsn & "'"
            cmd = New OdbcCommand(c, conn)
            cmd.ExecuteNonQuery()

            c = ""
            c = c & " insert prd_history_dataorder (iddtorder,idstatusproyek,waktu,userid) values "
            c = c & " ('" & iddtorder & "','21',now(),'" & userid & "')"
            cmd = New System.Data.Odbc.OdbcCommand(c, conn)
            cmd.ExecuteNonQuery()

            MsgBox("PO Telah di Terima !!..", MsgBoxStyle.Information, "Information")
            ListDetailPODsn.Enabled = True
            BtnEntryDsn.Enabled = True
            If BtnAccDsn.Caption = "KIRIM PO" Then
                BtnAccDsn.Enabled = True
                BtnAccDsn.DropDownEnabled = True
            Else
                BtnAccDsn.Enabled = False
            End If
            RbTerima.Checked = False
            RbKirim.Checked = True
        Else
            Return
        End If
        SqlDataSource1.FillAsync()
        BtnAccDsn.Enabled = False

    End Sub

    Private Sub BtnSelesai_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BtnSelesai.ItemClick
        GGVM_conn()
        Dim ada As Boolean
        Dim jmldt As Integer
        ada = False
        jmldt = 0
        For i = 0 To ListDetailPODsn.Items.Count - 1
            If ListDetailPODsn.Items(i).Checked = True Then
                ada = True
            End If
        Next
        If ada = False Then
            MsgBox("Tidak ada data yang akan di Selesaikan, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
            ListDetailPODsn.Focus()
            Exit Sub
        End If
        For Each item As ListViewItem In ListDetailPODsn.Items
            sql = ""
            sql = sql & "select * from prd_trans_detailpo_desain where idbarang = '" & item.SubItems(8).Text & "'"
            cmd = New OdbcCommand(sql, conn)
            dr = cmd.ExecuteReader
            dr.Read()
            If Not dr.HasRows Then
                MsgBox("Harap Kirim dulu Semua PO, Sebelum Menyelesaikan ", MsgBoxStyle.Information)
                Exit Sub
            Else
                c = ""
                c = c & " update po_desain set"
                c = c & " kirim_po = now(),kirim_ppic = now() , time_closhing = now()"
                c = c & " where idpo_dsn ='" & idpodsn & "'"
                cmd = New System.Data.Odbc.OdbcCommand(c, conn)
                cmd.ExecuteNonQuery()
            End If
        Next
        MsgBox("PO SUDAH DISELESAIKAN !!", MsgBoxStyle.Information)
        SqlDataSource1.FillAsync()
        'GGVM_conn_close()
    End Sub
    Private Sub ListDetailPODsn_DrawColumnHeader(sender As Object, e As DrawListViewColumnHeaderEventArgs) Handles ListDetailPODsn.DrawColumnHeader
        e.DrawDefault = True
    End Sub

    Private Sub ListDetailPODsn_DrawSubItem(sender As Object, e As DrawListViewSubItemEventArgs) Handles ListDetailPODsn.DrawSubItem
        Using txtbrsh As New SolidBrush(e.SubItem.ForeColor)
            If ListDetailPODsn.SelectedIndices.Contains(e.ItemIndex) And ListDetailPODsn.Focused Then
                e.Graphics.FillRectangle(New SolidBrush(Color.FromKnownColor(KnownColor.Highlight)), e.Bounds)
                txtbrsh.Color = Color.White
            End If
            Using sf As New StringFormat With {.Alignment = StringAlignment.Near, .LineAlignment = StringAlignment.Center, .FormatFlags = StringFormatFlags.NoWrap, .Trimming = StringTrimming.EllipsisCharacter}
                If e.Item.SubItems(1) Is e.SubItem Then
                    e.DrawDefault = False
                    Dim rb As New Rectangle(e.Bounds.X + e.Bounds.Height, e.Bounds.Y, e.Bounds.Width + e.Bounds.Height, e.Bounds.Height)
                    If e.Item.SubItems(15).Text <> "" And e.Item.SubItems(16).Text = "" Then
                        e.Graphics.DrawImage(My.Resources.message_prt, e.Bounds.X, e.Bounds.Y, e.Bounds.Height, e.Bounds.Height)
                    ElseIf e.Item.SubItems(16).Text <> "" And e.Item.SubItems(15).Text = "" Then
                        e.Graphics.DrawImage(My.Resources.message_cut, e.Bounds.X, e.Bounds.Y, e.Bounds.Height, e.Bounds.Height)
                    ElseIf e.Item.SubItems(15).Text <> "" And e.Item.SubItems(16).Text <> "" Then
                        e.Graphics.DrawImage(My.Resources.message, e.Bounds.X, e.Bounds.Y, e.Bounds.Height, e.Bounds.Height)
                    ElseIf e.Item.SubItems(17).Text = "Y" Then
                        e.Graphics.DrawImage(My.Resources._sub, e.Bounds.X, e.Bounds.Y, e.Bounds.Height, e.Bounds.Height)
                    End If
                    e.Graphics.DrawString(e.SubItem.Text, e.SubItem.Font, txtbrsh, rb, sf)
                Else
                    e.DrawDefault = True
                End If
            End Using
        End Using
    End Sub
    Private Sub BtnEditDsn_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BtnEditDsn.ItemClick
        Dim ada, item, cutting As Boolean
        Dim jmldt, jmldetail, brs, brs2, jmldetailcut As Integer
        ada = False
        item = False
        cutting = False
        jmldt = 0
        jmldetail = 0
        jmldetailcut = 0
        For i = 0 To ListDetailPODsn.Items.Count - 1
            If ListDetailPODsn.Items(i).Checked = True Then
                ada = True
                brs = i
                jmldt = jmldt + 1
            End If
        Next
        If ada = False Then
            MsgBox("Tidak ada data yang akan dipilih, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
            ListDetailPODsn.Focus()
            Exit Sub
        ElseIf jmldt > 1 Then
            MsgBox("Hanya 1(satu) data PO-DESIGN yg bisa di-Entry !!...", MsgBoxStyle.Information, "Information")
            Exit Sub
        End If

        For g = 0 To ListPOPrint.Items.Count - 1
            If ListPOPrint.Items(g).Checked = True Then
                item = True
                brs2 = g
                jmldetail = jmldetail + 1
            End If
        Next

       

        AutoCompBarangPrinting()
        For i = 0 To ListDetailPODsn.Items.Count - 1
            If ListDetailPODsn.Items(i).Checked = True Then
                brs = i
                TToko.Text = ListDetailPODsn.Items(i).SubItems(0).Text
                TKota.Text = ListDetailPODsn.Items(i).SubItems(1).Text
                TBarang1.Text = ListDetailPODsn.Items(i).SubItems(2).Text
                TBrand.Text = ListDetailPODsn.Items(i).SubItems(3).Text
                Tp1.Text = ListDetailPODsn.Items(i).SubItems(4).Text
                Tl1.Text = ListDetailPODsn.Items(i).SubItems(5).Text
                Tt1.Text = ListDetailPODsn.Items(i).SubItems(6).Text
                Tj1.Text = ListDetailPODsn.Items(i).SubItems(7).Text
                TIdBarang1.Text = ListDetailPODsn.Items(i).SubItems(9).Text
                TIdpoprd.Text = ListDetailPODsn.Items(i).SubItems(10).Text
                TIdToko.Text = ListDetailPODsn.Items(i).SubItems(11).Text
                TIdBrand.Text = ListDetailPODsn.Items(i).SubItems(12).Text
                TidDetailDsn.Text = ListDetailPODsn.Items(i).SubItems(14).Text
                TKeterangan.Text = ListDetailPODsn.Items(i).SubItems(15).Text
            End If
        Next

        If item = True And cutting = True Then
            MsgBox("Pilih salah satu data yang mau diedit, Cutting/Printing!!...", MsgBoxStyle.Information, "Information")
            ListDetailPODsn.Focus()
            Exit Sub
        ElseIf item = True And cutting = False Then
            For i = 0 To ListPOPrint.Items.Count - 1
                If ListPOPrint.Items(i).Checked = True Then
                    CPrinting.Checked = True
                    brs2 = i
                    TidDetailPoPrt.Text = ListPOPrint.Items(i).SubItems(8).Text
                    Tp2.Text = ListPOPrint.Items(i).SubItems(2).Text
                    Tl2.Text = ListPOPrint.Items(i).SubItems(3).Text
                    Tt2.Text = ListPOPrint.Items(i).SubItems(4).Text
                    Tj2.Text = ListPOPrint.Items(i).SubItems(6).Text
                    TBarang2.Text = ListPOPrint.Items(i).SubItems(1).Text
                    CBahan.Text = ListPOPrint.Items(i).SubItems(10).Text
                    TFinishing.Text = ListPOPrint.Items(i).SubItems(11).Text
                    TidBahan.Text = ListPOPrint.Items(i).SubItems(12).Text
                    TidFinishing.Text = ListPOPrint.Items(i).SubItems(13).Text
                    TidPoPrt.Text = ListPOPrint.Items(i).SubItems(14).Text
                End If
            Next
     
        ElseIf item = False Then
            MsgBox("Tidak ada data PO Printing yang akan dipilih, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
            ListPOPrint.Focus()
            Exit Sub
        ElseIf jmldetail > 1 Then
            MsgBox("Hanya 1(satu) data PO-PRINTING yg bisa di-Entry !!...", MsgBoxStyle.Information, "Information")
            Exit Sub
        ElseIf jmldetailcut > 1 Then
            MsgBox("Hanya 1(satu) data PO-CUTTING yg bisa di-Entry !!...", MsgBoxStyle.Information, "Information")
            Exit Sub
        End If
        EntryMode()
        Panel2.Visible = True
        Proses = "Edit"
    End Sub

    Private Sub ListDetailPODsn_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ListDetailPODsn.SelectedIndexChanged
        Me.Cursor = Cursors.WaitCursor
        With Me.ListDetailPODsn
            'For Each check As ListViewItem In ListDetailPODsn.CheckedItems
            '    check.Checked = False
            'Next
            For Each item As ListViewItem In ListDetailPODsn.SelectedItems
                item.Checked = True
                brske = item.Index
            Next
            TIdToko.Text = ListDetailPODsn.Items(brske).SubItems(11).Text
            'TIdBarang1.Text = ListDetailPODsn.Items(brske).SubItems(11).Text
        End With
        TampilDetailPrinting()
        Me.Cursor = Cursors.Default
    End Sub
    Private Sub CBahan_SelectedValueChanged(sender As Object, e As EventArgs) Handles CBahan.SelectedValueChanged
        GGVM_conn()
        s = "select idbahan from prd_bahan_printing where bahan= '" & CBahan.Text & "'"
        cmd = New OdbcCommand(s, conn)
        dr = cmd.ExecuteReader
        dr.Read()
        If Not dr.HasRows Then
            TidBahan.Text = ""
        Else
            TidBahan.Text = dr.Item("idbahan")
        End If
        GGVM_conn_close()
    End Sub
    Private Panel1Captured As Boolean
    Private Panel1Grabbed As Point

    Private Sub Panel1_MouseDown(ByVal sender As Object, ByVal e As System.Windows.Forms.MouseEventArgs) Handles Panel2.MouseDown
        Panel1Captured = True
        Panel1Grabbed = e.Location
    End Sub

    Private Sub Panel1_MouseMove(ByVal sender As Object, ByVal e As System.Windows.Forms.MouseEventArgs) Handles Panel2.MouseMove
        If (Panel1Captured) Then Panel2.Location = Panel2.Location + e.Location - Panel1Grabbed
    End Sub

    Private Sub Panel1_MouseUp(ByVal sender As Object, ByVal e As System.Windows.Forms.MouseEventArgs) Handles Panel2.MouseUp
        Panel1Captured = False
    End Sub
End Class
