Imports System.ComponentModel
Imports System.ComponentModel.DataAnnotations
Imports DevExpress.XtraBars
Imports DevExpress.XtraEditors
Imports DevExpress.Utils

Partial Public Class DataOrder

    Public Sub New()
        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill the SqlDataSource asynchronously
        SqlDataSource1.FillAsync()
    End Sub

    Private Sub windowsUIButtonPanel_ButtonClick(ByVal sender As Object, ByVal e As DevExpress.XtraBars.Docking2010.ButtonEventArgs) Handles windowsUIButtonPanel.ButtonClick
        If e.Button.Properties.Caption = "Print" Then
            gridControl.ShowRibbonPrintPreview()
        ElseIf e.Button.Properties.Caption = "New" Then
            Proses = "entry"
            FlyoutPanel1.Options.AnimationType = DevExpress.Utils.Win.PopupToolWindowAnimation.Fade
            FlyoutPanelControl1.Controls.Add(New EntryDO() With {
            .Dock = DockStyle.Fill
             })
            FlyoutPanel1.ShowPopup()
            
        ElseIf e.Button.Properties.Caption = "Edit" Then

        ElseIf e.Button.Properties.Caption = "Delete" Then
           
        ElseIf e.Button.Properties.Caption = "Refresh" Then
            SqlDataSource1.FillAsync()
        End If
    End Sub

    Private Sub DataOrder_Load(sender As Object, e As EventArgs) Handles Me.Load

    End Sub

    Private Sub FlyoutPanel1_ButtonClick(sender As Object, e As DevExpress.Utils.FlyoutPanelButtonClickEventArgs) Handles FlyoutPanel1.ButtonClick
        Dim tag As String = e.Button.Tag.ToString()
        Select Case tag
            Case "accept"
                ' . . .
            Case "Close"
                Dim Entry As New EntryDO
                FlyoutPanelControl1.Controls.Clear()
                Entry.Dispose()
                Entry.Hide()
                ' . . .
                'EntryDO.Dispose()
                TryCast(sender, FlyoutPanel).HidePopup()
        End Select
    End Sub
End Class
