Imports System.ComponentModel
Imports System.ComponentModel.DataAnnotations
Imports DevExpress.XtraBars
Imports DevExpress.XtraEditors
Imports DevExpress.Utils
Imports System.Windows.Forms.AxHost
Imports System.Runtime.CompilerServices
Imports DevExpress.XtraGrid.Columns
Imports DevExpress.XtraGrid.Views.Base

Partial Public Class DataOrder
    Friend Shared Event GetTextBoxText(ByVal myString As String)
    Friend Shared Event GetNoDo(ByVal NoDo As String)
    Friend Shared Event GetBrand(ByVal NoDo As String)
    Friend Shared Event GetKlien(ByVal NoDo As String)
    Friend Shared Event GetProyek(ByVal NoDo As String)
    Friend Shared Event GetDeadline(ByVal NoDo As String)
    Friend Shared Event GetDivIDSurvei(ByVal NoDo As String)
    Friend Shared Event GetDivSurvei(ByVal NoDo As String)
    Dim nodo, divisi, idivisi_survei, survei, tanggal, klien, idklien, brand, idbrand, proyek, deadline As String
    Public Sub New()
        InitializeComponent()

        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill the SqlDataSource asynchronously
        SqlDataSource1.FillAsync()
    End Sub

    Private Sub windowsUIButtonPanel_ButtonClick(ByVal sender As Object, ByVal e As DevExpress.XtraBars.Docking2010.ButtonEventArgs) Handles windowsUIButtonPanel.ButtonClick
        If e.Button.Properties.Caption = "Print" Then
            gridControl.ShowRibbonPrintPreview()
        ElseIf e.Button.Properties.Caption = "New" Then
            Proses = "entry"
            FlyoutPanel1.Options.AnimationType = DevExpress.Utils.Win.PopupToolWindowAnimation.Fade
            FlyoutPanelControl1.Controls.Add(New EntryDO() With {
            .Dock = DockStyle.Fill
             })
            FlyoutPanel1.ShowPopup()

        ElseIf e.Button.Properties.Caption = "Edit" Then
            If TidDtOrder.Text = "" Then
                MsgBox(" Pilih dulu Data Ordernya !! ", MsgBoxStyle.Information, "Pemberitahuan !!")
                Exit Sub
            End If
            Proses = "edit"

            FlyoutPanel1.Options.AnimationType = DevExpress.Utils.Win.PopupToolWindowAnimation.Fade
            FlyoutPanelControl1.Controls.Add(New EntryDO() With {
            .Dock = DockStyle.Fill
             })
            RaiseEvent GetTextBoxText(TidDtOrder.Text)
            RaiseEvent GetNoDo(nodo)
            RaiseEvent GetProyek(proyek)
            RaiseEvent GetKlien(klien)
            RaiseEvent GetBrand(brand)
            RaiseEvent GetDeadline(deadline)
            RaiseEvent GetDivIDSurvei(idivisi_survei)
            RaiseEvent GetDivSurvei(survei)
            FlyoutPanel1.ShowPopup()
        ElseIf e.Button.Properties.Caption = "Delete" Then

        ElseIf e.Button.Properties.Caption = "Refresh" Then
            SqlDataSource1.FillAsync()
        ElseIf e.Button.Properties.Caption = "Detail Toko" Then
            If TidDtOrder.Text = "" Then
                MsgBox(" Pilih dulu Data Ordernya !! ", MsgBoxStyle.Information, "Pemberitahuan !!")
                Exit Sub
            End If
            ProsesDetail = "EntryDetail"
            FlyoutPanel1.Options.AnimationType = DevExpress.Utils.Win.PopupToolWindowAnimation.Fade
            FlyoutPanelControl1.Controls.Add(New DetailToko() With {
            .Dock = DockStyle.Fill
             })
            FlyoutPanel1.Height = Height
            RaiseEvent GetTextBoxText(TidDtOrder.Text)
            FlyoutPanel1.ShowPopup()
        ElseIf e.Button.Properties.Caption = "Keluar" Then
            Me.Dispose()
        End If
    End Sub

    Private Sub DataOrder_Load(sender As Object, e As EventArgs) Handles Me.Load


    End Sub

    Private Sub FlyoutPanel1_ButtonClick(sender As Object, e As DevExpress.Utils.FlyoutPanelButtonClickEventArgs) Handles FlyoutPanel1.ButtonClick
        Dim tag As String = e.Button.Tag.ToString()
        Select Case tag
            Case "accept"
                ' . . .
            Case "Close"
                Dim Entry As New EntryDO
                Dim TokoDetail As New DetailToko
                FlyoutPanelControl1.Controls.Clear()
                Entry.Dispose()
                Entry.Hide()
                TokoDetail.Dispose()
                'TokoDetail.Visible = False
                ' . . .
                'EntryDO.Dispose()
                TryCast(sender, FlyoutPanel).HidePopup()
        End Select
    End Sub

    Private Sub gridControl_Click(sender As Object, e As EventArgs) Handles gridControl.Click

    End Sub



    Private Sub gridControl_DoubleClick(sender As Object, e As EventArgs) Handles gridControl.DoubleClick

    End Sub

    Private Sub AdvBandedGridView1_RowCellClick(sender As Object, e As DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs) Handles AdvBandedGridView1.RowCellClick
        TidDtOrder.Text = ""
        nodo = ""
        divisi = ""
        idivisi_survei = ""
        tanggal = ""
        klien = ""
        idklien = ""
        brand = ""
        idbrand = ""
        proyek = ""
        survei = ""
        deadline = ""
        TidDtOrder.Text = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "iddtorder").ToString()
        nodo = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "noorder").ToString()
        divisi = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "divisi").ToString()
        idivisi_survei = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "iddivisi_survei").ToString()
        tanggal = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "tglorder").ToString()
        klien = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "nmklien").ToString()
        idklien = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "idklien").ToString()
        brand = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "brand").ToString()
        idbrand = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "idbrand").ToString()
        proyek = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "namaorder").ToString()
        deadline = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "deadline_ki").ToString()
        survei = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "survei").ToString()
    End Sub

    Private Sub AdvBandedGridView1_SelectionChanged(sender As Object, e As DevExpress.Data.SelectionChangedEventArgs) Handles AdvBandedGridView1.SelectionChanged
        TidDtOrder.Text = ""
        nodo = ""
        divisi = ""
        idivisi_survei = ""
        tanggal = ""
        klien = ""
        idklien = ""
        brand = ""
        idbrand = ""
        survei = ""
        proyek = ""
        deadline = ""
        TidDtOrder.Text = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "iddtorder").ToString()
        nodo = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "noorder").ToString()
        divisi = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "divisi").ToString()
        idivisi_survei = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "iddivisi_survei").ToString()
        tanggal = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "tglorder").ToString()
        klien = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "nmklien").ToString()
        idklien = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "idklien").ToString()
        brand = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "brand").ToString()
        idbrand = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "idbrand").ToString()
        proyek = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "namaorder").ToString()
        deadline = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "deadline_ki").ToString()
        survei = AdvBandedGridView1.GetRowCellValue(AdvBandedGridView1.FocusedRowHandle, "survei").ToString()
    End Sub



    Private Sub labelControl_Click(sender As Object, e As EventArgs) Handles labelControl.Click

    End Sub

    Private Sub windowsUIButtonPanel_Click(sender As Object, e As EventArgs) Handles windowsUIButtonPanel.Click

    End Sub
End Class
