Imports DevExpress.Utils
Imports System.Data.Odbc

Public Class DetailDataOrder
    Friend Shared Event GetDataOrder(ByVal idDO As String)
    Dim iddo As String

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill the SqlDataSource asynchronously
        SqlDataSource1.FillAsync()
    End Sub

    Private Sub WindowsUIButtonPanel1_ButtonClick(sender As Object, e As DevExpress.XtraBars.Docking2010.ButtonEventArgs) Handles WindowsUIButtonPanel1.ButtonClick
        If e.Button.Properties.Caption = "Print" Then
            GridControl2.ShowRibbonPrintPreview()
        ElseIf e.Button.Properties.Caption = "Detail D.O" Then
            Proses = "entry"
            FlyoutPanel1.Options.AnimationType = DevExpress.Utils.Win.PopupToolWindowAnimation.Fade
            FlyoutPanelControl1.Controls.Add(New StatusSurvei() With {
            .Dock = DockStyle.Fill
             })
            RaiseEvent GetDataOrder(iddo)
            FlyoutPanel1.Width = ClientSize.Width
            FlyoutPanel1.Height = 620
            FlyoutPanel1.ShowPopup()
        ElseIf e.Button.Properties.Caption = "Refresh" Then
            SqlDataSource1.FillAsync()
        ElseIf e.Button.Properties.Caption = "Keluar" Then
            Me.Dispose()
        End If
    End Sub

    Private Sub FlyoutPanel1_ButtonClick(sender As Object, e As DevExpress.Utils.FlyoutPanelButtonClickEventArgs) Handles FlyoutPanel1.ButtonClick
        Dim tag As String = e.Button.Tag.ToString()
        Dim Status As New StatusSurvei
        Select Case tag
            Case "Tutup"

                'Dim TokoDetail As New DetailToko
                FlyoutPanelControl1.Controls.Clear()
                Status.Dispose()
                Status.Hide()
                ' . . .
                'EntryDO.Dispose()
                TryCast(sender, FlyoutPanel).HidePopup()
        End Select
    End Sub

    Private Sub GridView3_RowCellClick(sender As Object, e As DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs) Handles GridView3.RowCellClick
        iddo = ""
        iddo = GridView3.GetRowCellValue(GridView3.FocusedRowHandle, "IDDTORDER").ToString()
        ListDetailDO.BeginUpdate()
        Try
            ListDetailDO.Items.Clear()
            TampilDetailDo()
        Finally
            ListDetailDO.EndUpdate()
        End Try
    End Sub

    Private Sub GridView3_SelectionChanged(sender As Object, e As DevExpress.Data.SelectionChangedEventArgs) Handles GridView3.SelectionChanged
        iddo = ""
        iddo = GridView3.GetRowCellValue(GridView3.FocusedRowHandle, "IDDTORDER").ToString()
        ListDetailDO.BeginUpdate()
        Try
            ListDetailDO.Items.Clear()
            TampilDetailDo()
        Finally
            ListDetailDO.EndUpdate()
        End Try
    End Sub
    Private Sub ListHeaderDetaildo()
        ListDetailDO.FullRowSelect = True
        ListDetailDO.MultiSelect = True
        ListDetailDO.View = View.Details
        'ListDetailDO.CheckBoxes = True
        ListDetailDO.Columns.Clear()
        ListDetailDO.Items.Clear()
        ListDetailDO.Columns.Add("BARANG", 200, HorizontalAlignment.Left)
        ListDetailDO.Columns.Add("HARGA", 75, HorizontalAlignment.Right)
        ListDetailDO.Columns.Add("PANJANG", 100, HorizontalAlignment.Right)
        ListDetailDO.Columns.Add("TINGGI", 100, HorizontalAlignment.Right)
        ListDetailDO.Columns.Add("LEBAR", 100, HorizontalAlignment.Right)
        ListDetailDO.Columns.Add("P x T", 100, HorizontalAlignment.Right)
        ListDetailDO.Columns.Add("SISI", 100, HorizontalAlignment.Right)
        ListDetailDO.Columns.Add("MEASURE", 100, HorizontalAlignment.Right)
        ListDetailDO.Columns.Add("QTY", 80, HorizontalAlignment.Right)
        ListDetailDO.Columns.Add("TOTAL", 130, HorizontalAlignment.Right)
        ListDetailDO.Columns.Add("MATERIAL", 100, HorizontalAlignment.Left)
        ListDetailDO.Columns.Add("KETERANGAN", 100, HorizontalAlignment.Left)
        ListDetailDO.Columns.Add("QTY-TK", 80, HorizontalAlignment.Right)
        ListDetailDO.Columns.Add("idbarang", 1, HorizontalAlignment.Left)
        ListDetailDO.Columns.Add("idmaterial", 1, HorizontalAlignment.Left)
        ListDetailDO.Columns.Add("iddetaildo", 1, HorizontalAlignment.Left)
        ListDetailDO.Columns.Add("SATUAN", 1, HorizontalAlignment.Left)

    End Sub
    Private Sub TampilDetailDo()
        Dim s As String
        Dim i As Integer
        Dim tbl As New DataTable

        ListDetailDO.Items.Clear()
        GGVM_conn()
        s = ""
        s = s & " select * from view_detaildo "
        s = s & " where iddtorder = '" & iddo & "'"
        s = s & " GROUP BY iddetailpe "
        da = New OdbcDataAdapter(s, conn)
        'ds.Clear()
        tbl = New DataTable
        tbl.Clear()
        da.Fill(tbl)

        For i = 0 To tbl.Rows.Count - 1
            With ListDetailDO
                .Items.Add(tbl.Rows(i)("barang"))
                With .Items(.Items.Count - 1).SubItems
                    .Add(FormatNumber(tbl.Rows(i)("harga_barang"), 0, , , TriState.True))
                    .Add(tbl.Rows(i)("panjang_pe"))
                    .Add(tbl.Rows(i)("tinggi_pe"))
                    .Add(tbl.Rows(i)("lebar_pe"))
                    .Add(tbl.Rows(i)("size_pe"))
                    .Add(tbl.Rows(i)("sisi_pe"))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("measure_pe")), "", tbl.Rows(i)("measure_pe")))
                    .Add(tbl.Rows(i)("qty_pe"))
                    .Add(FormatNumber(tbl.Rows(i)("harga_PE"), 0, , , TriState.True))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("material")), "", tbl.Rows(i)("material")))
                    .Add(tbl.Rows(i)("keterangan"))
                    .Add(tbl.Rows(i)("qty_TOKO"))
                    .Add(tbl.Rows(i)("idbarang"))
                    .Add(IIf(IsDBNull(tbl.Rows(i)("idmaterial")), "", tbl.Rows(i)("idmaterial")))
                    .Add(tbl.Rows(i)("iddetailpe"))
                    .Add(tbl.Rows(i)("SATUAN"))
                End With
            End With
        Next
        GGVM_conn_close()
    End Sub

    Private Sub DetailDataOrder_Load(sender As Object, e As EventArgs) Handles Me.Load
        ListHeaderDetaildo()
    End Sub

    Private Sub FlyoutPanel1_Load(sender As Object, e As EventArgs) Handles FlyoutPanel1.Load

    End Sub

    Private Sub WindowsUIButtonPanel1_Click(sender As Object, e As EventArgs) Handles WindowsUIButtonPanel1.Click

    End Sub
End Class
