Imports System.Data.Odbc
Imports DevExpress.XtraEditors

Public Class EntryDO

    Public Sub New()
        InitializeComponent()

        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill the SqlDataSource asynchronously
        AddHandler DataOrder.GetTextBoxText, AddressOf SetLabelText
        AddHandler DataOrder.GetNoDo, AddressOf SetTextNoDo
        AddHandler DataOrder.GetKlien, AddressOf SetTextKlien
        AddHandler DataOrder.GetBrand, AddressOf SetTextBrand
        AddHandler DataOrder.GetProyek, AddressOf SetTextProyek
        AddHandler DataOrder.GetDeadline, AddressOf SetTextDeadline
        AddHandler DataOrder.GetDivIDSurvei, AddressOf SetTextIDSurvei
        AddHandler DataOrder.GetDivSurvei, AddressOf SetTextSurvei

        'TampilToko()
    End Sub
    Private Sub SetLabelText(ByVal myString As String)
        TidDtOrder.Text = myString
    End Sub
    Private Sub SetTextNoDo(ByVal NoDo As String)
        TNoDo.Text = NoDo
    End Sub
    Private Sub SetTextKlien(ByVal NoDo As String)
        TKlien.Text = NoDo
    End Sub
    Private Sub SetTextBrand(ByVal NoDo As String)
        TBrand.Text = NoDo
    End Sub
    Private Sub SetTextProyek(ByVal NoDo As String)
        TProyek.Text = NoDo
    End Sub
    Private Sub SetTextDeadline(ByVal NoDo As String)
        DTDeadlineKI.Text = NoDo
    End Sub
    Private Sub SetTextIDSurvei(ByVal NoDo As String)
        IDSurvei.Text = NoDo
    End Sub
    Private Sub SetTextSurvei(ByVal NoDo As String)
        If NoDo = "N" Then
            SURVEI.Checked = False
        ElseIf NoDo = "Y" Then
            SURVEI.Checked = True
            RadioGroup1.Enabled = True
            If IDSurvei.Text = "1" Then
                RadioGroup1.SelectedIndex = 0
            ElseIf IDSurvei.Text = "5" Then
                RadioGroup1.SelectedIndex = 1
            ElseIf IDSurvei.Text = "V" Then
                RadioGroup1.SelectedIndex = 2
            Else
                SURVEI.Checked = False
            End If
        End If
    End Sub
    Private Sub ListHeaderDistributor()
        ListKota.FullRowSelect = True
        ListKota.MultiSelect = True
        ListKota.View = View.Details
        ListKota.CheckBoxes = True
        ListKota.Columns.Clear()
        ListKota.Items.Clear()
        ListKota.Columns.Add("DISTRIBUTOR", 200, HorizontalAlignment.Left)
        ListKota.Columns.Add("TOKO", 200, HorizontalAlignment.Left)
        ListKota.Columns.Add("IDDist", 1, HorizontalAlignment.Left)
        ListKota.Columns.Add("IDTOKO", 1, HorizontalAlignment.Left)
        ListKota.Columns.Add("IDKirim", 1, HorizontalAlignment.Left)
    End Sub


    Public Sub TampilPenerima()
        GGVM_conn()
        Dim s As String
        Dim tbl As New DataTable
        s = ""
        s = s & " select a.idkirim, if (d.`distributor` is null,'',d.`distributor`) as distributor, "
        s = s & " if (c.toko is null,'', c.toko) as toko, if(a.idtoko is null,'',a.idtoko) as idtoko,"
        s = s & "  if (a.iddist is null,'',a.iddist) as iddist from prd_kirim_dataorder a"
        s = s & " left join prd_dataorder b on b.iddtorder = a.iddtorder"
        s = s & " left join prd_toko c on c.idtoko = a.`idtoko` "
        s = s & " left join distributor d on d.iddist = a.iddist "
        s = s & " where a.iddtorder ='" & TidDtOrder.Text & "'"
        da = New OdbcDataAdapter(s, conn)
        'ds.Clear()
        ListKota.Items.Clear()
        tbl = New DataTable
        tbl.Clear()
        da.Fill(tbl)

        For i = 0 To tbl.Rows.Count - 1
            With ListKota
                .Items.Add(tbl.Rows(i)("distributor"))
                With .Items(.Items.Count - 1).SubItems
                    .Add(tbl.Rows(i)("toko"))
                    .Add(tbl.Rows(i)("iddist"))
                    .Add(tbl.Rows(i)("idtoko"))
                    .Add(tbl.Rows(i)("idkirim"))
                End With
            End With
        Next
        GGVM_conn_close()
        Me.Cursor = Cursors.Default
    End Sub
    Private Sub TampilKlien()
        GGVM_conn()
        Dim s As String
        s = ""
        s = s & " select y.* from ( select nama,id from klien"
        s = s & " where status='1'"
        s = s & " and nama like '%" & TKlien.Text & "%'"
        s = s & " order by nama ) y "
        da = New OdbcDataAdapter(s, conn)
        ds = New DataSet
        da.Fill(ds)
        Dim Klien As New AutoCompleteStringCollection
        For i As Integer = 0 To ds.Tables(0).Rows.Count - 1
            Klien.Add(ds.Tables(0).Rows(i)("nama").ToString())
        Next
        With TKlien
            .AutoCompleteSource = AutoCompleteSource.CustomSource
            .AutoCompleteCustomSource = Klien
            .AutoCompleteMode = AutoCompleteMode.Suggest
        End With
        GGVM_conn_close()
    End Sub
    Private Sub TampilBrand()
        GGVM_conn()
        Dim s As String
        s = ""
        s = s & " select y.* from (select brand,idbrand from brand"
        s = s & " where status='1'"
        ' s = s & " and idklien ='" & TIDKlien.Text & "'"
        s = s & " and brand like '%" & TBrand.Text & "%'"
        s = s & " order by brand ) y"
        da = New OdbcDataAdapter(s, conn)
        ds = New DataSet
        da.Fill(ds)
        Dim Brand As New AutoCompleteStringCollection
        For i As Integer = 0 To ds.Tables(0).Rows.Count - 1
            Brand.Add(ds.Tables(0).Rows(i)("brand").ToString())
        Next
        With TBrand
            .AutoCompleteSource = AutoCompleteSource.CustomSource
            .AutoCompleteCustomSource = Brand
            .AutoCompleteMode = AutoCompleteMode.Suggest
        End With
        GGVM_conn_close()
    End Sub
    Public Sub ClearInput()
        BtnSimpan.Enabled = True
        BtnSimpanToko.Enabled = True
        BtnHapusPenerima.Enabled = True
        TNoDo.Text = ""
        TidDtOrder.Text = ""
        TIDKlien.Text = ""
        TKlien.Text = ""
        TIDBrand.Text = ""
        TBrand.Text = ""
        TPenerima.Text = ""
        TProyek.Text = ""
        DTDeadlineKI.Enabled = True
        DTDeadlineKI.Format = DateTimePickerFormat.Custom
        DTDeadlineKI.CustomFormat = "dd/MM/yyyy"
        DTTanggal.Enabled = True
        DTTanggal.Format = DateTimePickerFormat.Custom
        DTTanggal.CustomFormat = "dd/MM/yyyy"
        SURVEI.Checked = False
        RadioGroup1.Enabled = True
        TProyek.Enabled = True
        SURVEI.Enabled = True
        TKlien.Enabled = True
        TBrand.Enabled = True
        CDist.Enabled = True
        CToko.Enabled = True
        TProyek.ReadOnly = False
        BtnSimpan.Enabled = True
        TPenerima.ReadOnly = True

    End Sub
    Private Sub BtnSimpan_Click(sender As Object, e As EventArgs) Handles BtnSimpan.Click
        Dim thndo, urutdo, nmProyek As String
        Dim count As Integer
        Dim tbl As DataTable
        Dim s, c As String
        Dim cmd As New OdbcCommand

        Me.Cursor = Cursors.WaitCursor
        nmProyek = replaceNewLine(TProyek.Text, True)
        Select Case Proses
            Case "entry"
                If MsgBox("Apakah anda yakin untuk menyimpan Data Order ?..", MsgBoxStyle.YesNo, "Question") = MsgBoxResult.Yes Then
                    If TIDDivisi.Text = "" Then
                        Me.Cursor = Cursors.Default
                        MsgBox(" Pilih dulu DIVISI nya !!...", MsgBoxStyle.Information, "Information")
                        Exit Sub
                    End If
                    If SURVEI.Checked = True Then
                        If IDSurvei.Text = "" Then
                            Me.Cursor = Cursors.Default
                            MsgBox("Pilih dulu yang Survei....DataOrder atau Marketing !!...", MsgBoxStyle.Information, "Information")
                            Exit Sub
                        End If
                    End If
                End If

                GGVM_conn()

                sql = "select nodo,tahundo from counter "
                cmd = New OdbcCommand(sql, conn)
                dr = cmd.ExecuteReader
                dr.Read()
                thndo = Microsoft.VisualBasic.Right(DTTanggal.Text, 4)

                If thndo = dr.GetString(1) Then
                    count = dr.Item("nodo")
                Else
                    count = 0
                End If
                count = count + 1
                urutdo = Microsoft.VisualBasic.Right("00000" & count, 5)
                TNoDo.Text = urutdo

                c = ""
                If count = 1 Then
                    c = c & " update counter set nodo = '" & count & "',"
                    c = c & " tahundo = '" & Microsoft.VisualBasic.Right(DTTanggal.Text, 4) & "'"
                Else
                    c = c & " update counter set nodo = '" & count & "'"
                End If
                cmd = New OdbcCommand(c, conn)
                cmd.ExecuteNonQuery()
                c = ""
                c = c & " insert prd_dataorder (iddivisi,noorder,tglorder,idklien,"
                If TIDBrand.Text <> "" Then
                    c = c & "idbrand,"
                End If
                c = c & " namaorder,"
                If SURVEI.Checked = True Then
                    c = c & " survei, iddivisi_survei, "
                End If
                c = c & " deadline_ki,"
                c = c & " idstatus_proyek,user_input,time_input) values"
                c = c & " ('" & TIDDivisi.Text & "','" & urutdo & "','" & Format(DTTanggal.Value, "yyyy/MM/dd") & "','" & TIDKlien.Text & "',"
                If TIDBrand.Text <> "" Then
                    c = c & "'" & TIDBrand.Text & "',"
                End If
                c = c & "'" & nmProyek & "',"
                If SURVEI.Checked = True Then
                    c = c & " 'Y',"
                    c = c & " '" & IDSurvei.Text & "',"
                End If
                c = c & "'" & Format(DTDeadlineKI.Value, "yyyy/MM/dd") & "',"
                c = c & "'1','" & userid & "',now())"
                cmd = New System.Data.Odbc.OdbcCommand(c, conn)
                cmd.ExecuteNonQuery()

                s = ""
                s = s & " select max(iddtorder)as id from prd_dataorder "
                da = New System.Data.Odbc.OdbcDataAdapter(s, conn)
                tbl = New DataTable
                tbl.Clear()
                da.Fill(tbl)
                TidDtOrder.Text = tbl.Rows(0)("id")

                c = ""
                c = c & " insert prd_history_dataorder (iddtorder,idstatusproyek,waktu,userid) values "
                c = c & " ('" & TidDtOrder.Text & "','1',now(),'" & userid & "')"
                cmd = New System.Data.Odbc.OdbcCommand(c, conn)
                cmd.ExecuteNonQuery()

                GGVM_conn_close()
                Me.Cursor = Cursors.Default
                MsgBox("Data sudah diSIMPAN !!...", MsgBoxStyle.Information, "Information")
                BtnSimpan.Enabled = False

                MsgBox("Masukkan Daftar Toko !!...", MsgBoxStyle.Information, "Information")
                CDist.Enabled = True
                CToko.Enabled = True
                BtnSimpanToko.Enabled = True
                BtnHapusPenerima.Enabled = True
                'BtnEntryToko.Enabled = True
                TPenerima.Enabled = True
                TPenerima.ReadOnly = False
            Case "edit"

                GGVM_conn()
                c = ""
                c = c & " update prd_dataorder set "
                c = c & " iddivisi = '" & TIDDivisi.Text & "',"
                c = c & " idklien = '" & TIDKlien.Text & "',"
                If TIDBrand.Text <> "" Then
                    c = c & "idbrand = '" & TIDBrand.Text & "',"
                End If
                c = c & " namaorder = '" & nmProyek & "',"
                If SURVEI.Checked = True Then
                    c = c & " survei = 'Y',"
                    c = c & " iddivisi_survei='" & IDSurvei.Text & "',"
                End If
                c = c & " deadline_ki ='" & Format(DTDeadlineKI.Value, "yyyy/MM/dd") & "', "
                c = c & " user_koreksi ='" & userid & "',time_koreksi=now()"
                c = c & " where iddtorder = '" & TidDtOrder.Text & "'"
                cmd = New System.Data.Odbc.OdbcCommand(c, conn)
                cmd.ExecuteNonQuery()
                GGVM_conn_close()
                Me.Cursor = Cursors.Default
                MsgBox("Data sudah diUPDATE !!...", MsgBoxStyle.Information, "Information")
                BtnSimpanToko.Enabled = True
                BtnHapusPenerima.Enabled = True
                'BtnEntryToko.Enabled = True
                TPenerima.Enabled = True
                TPenerima.ReadOnly = False
                CDist.Enabled = True
                CToko.Enabled = True
        End Select
        'TampilDO()
        'TokoDistributor1.Enabled = True
        'ListDO.Enabled = False
        'DataOrder.FlyoutPanelControl1.Controls.Clear()
        'DataOrder.FlyoutPanel1.HidePopup()
        Me.Cursor = Cursors.Default
    End Sub

    Private Sub BtnBatal_Click(sender As Object, e As EventArgs)

        Dim DataO As New DataOrder
        DataO.FlyoutPanel1.HidePopup()
        'DataO.GroupEntry.Dispose()
        Me.Dispose()

    End Sub

    Private Sub EntryDO_HandleDestroyed(sender As Object, e As EventArgs) Handles Me.HandleDestroyed
        Me.Dispose()
    End Sub

    Private Sub EntryDO_Load(sender As Object, e As EventArgs) Handles Me.Load
        'ClearInput()
        TampilKlien()
        TampilBrand()
        DTDeadlineKI.Format = DateTimePickerFormat.Custom
        DTDeadlineKI.CustomFormat = "dd/MM/yyyy"
        DTDeadlineKI.Value = DateTime.Now
        TIDDivisi.Text = DivUser
        ListHeaderDistributor()
        TampilPenerima()
        ' LoaddEdit()
    End Sub

    Private Sub TKlien_TextChanged(sender As Object, e As EventArgs) Handles TKlien.TextChanged
        Dim s As String
        GGVM_conn()
        s = "select id from klien where nama= '" & TKlien.Text & "'"
        cmd = New OdbcCommand(s, conn)
        dr = cmd.ExecuteReader
        dr.Read()
        If Not dr.HasRows Then
            TIDKlien.Text = ""
        Else
            TIDKlien.Text = dr.Item("id")
        End If
        GGVM_conn_close()
    End Sub

    Private Sub TBrand_TextChanged(sender As Object, e As EventArgs) Handles TBrand.TextChanged
        Dim s As String
        GGVM_conn()
        s = "select idbrand from brand where brand= '" & TBrand.Text & "'"
        cmd = New OdbcCommand(s, conn)
        dr = cmd.ExecuteReader
        dr.Read()
        If Not dr.HasRows Then
            TIDBrand.Text = ""
        Else
            TIDBrand.Text = dr.Item("idbrand")
        End If
        GGVM_conn_close()
    End Sub

    Private Sub RadioGroup1_SelectedIndexChanged(sender As Object, e As EventArgs) Handles RadioGroup1.SelectedIndexChanged
        Dim radioGroup = TryCast(sender, RadioGroup)
        If radioGroup.SelectedIndex = 0 Then
            IDSurvei.Text = "1"
        End If
        If radioGroup.SelectedIndex = 1 Then
            IDSurvei.Text = "5"
        End If
        If radioGroup.SelectedIndex = 2 Then
            IDSurvei.Text = "V"
        End If
    End Sub

    Private Sub SURVEI_CheckedChanged(sender As Object, e As EventArgs) Handles SURVEI.CheckedChanged
        If SURVEI.Checked = True Then
            RadioGroup1.Enabled = True
        Else
            RadioGroup1.Enabled = False
            RadioGroup1.EditValue = ""
            IDSurvei.Text = ""
        End If
    End Sub

    Private Sub BtnSimpanToko_Click(sender As Object, e As EventArgs) Handles BtnSimpanToko.Click
        Select Case Proses
            Case "entry"
                If TidDtOrder.Text = "" Then
                    MsgBox(" Simpan dulu Data Ordernya !!..", MsgBoxStyle.Information, "Information")
                    Exit Sub
                End If
                Try
                    GGVM_conn()
                    For Each item As ListViewItem In ListKota.Items
                        Dim sql As String = " INSERT INTO prd_kirim_dataorder (iddtorder,iddist,idtoko) VALUES (?, ?, ?)"
                        cmd = New OdbcCommand
                        With cmd
                            .CommandText = (sql)
                            .Parameters.Add("@iddtorder", OdbcType.VarChar).Value = TidDtOrder.Text
                            .Parameters.Add("@iddist", OdbcType.Double).Value = Convert.ToDouble(item.SubItems(2).Text)
                            .Parameters.Add("@idtoko", OdbcType.VarChar).Value = Convert.ToInt32(item.SubItems(3).Text)
                            .Connection = conn
                        End With
                        dr = cmd.ExecuteReader
                        Console.WriteLine(cmd.CommandText.ToString)
                        While dr.Read
                            Console.WriteLine(dr(0))
                            Console.WriteLine()
                        End While
                        Console.ReadLine()
                        ' conn.Close()
                        dr = Nothing
                        cmd = Nothing
                    Next
                    MsgBox(" Data Toko Berhasil Disimpan!..", MsgBoxStyle.Information, "Information")
                    BtnSimpanToko.Enabled = False
                    BtnHapusPenerima.Enabled = False
                    ListKota.Enabled = False
                    TPenerima.Enabled = False
                    CDist.Enabled = False
                    CToko.Enabled = False
                    BtnSimpanToko.Enabled = False
                    BtnHapusPenerima.Enabled = False
                    'BtnEntryToko.Enabled = True
                Catch ex As Exception
                    MessageBox.Show(ex.ToString)
                Finally
                    GGVM_conn_close()
                End Try
                'ListKota.Items.Clear()
                ClearInput()
                GridPanel.DataSource = Nothing
                BtnEntry.Enabled = True
                'BtnEdit.Enabled = True
                'BtnCetak.Enabled = True
                'TampilDO()
                BtnSimpan.Enabled = False


                TNoDo.Text = ""
                TidDtOrder.Text = ""
                TIDKlien.Text = ""
                TKlien.Text = ""
                TIDBrand.Text = ""
                TBrand.Text = ""
                TPenerima.Text = ""
                TProyek.Text = ""
                DTDeadlineKI.Format = DateTimePickerFormat.Custom
                DTDeadlineKI.CustomFormat = "dd/MM/yyyy"
                DTTanggal.Format = DateTimePickerFormat.Custom
                DTTanggal.CustomFormat = "dd/MM/yyyy"
                SURVEI.Checked = False
                TProyek.Enabled = False
                SURVEI.Enabled = False
            Case "edit"
                'ListKota.Items.Clear()
                ClearInput()
                GridPanel.DataSource = Nothing
                BtnEntry.Enabled = True
                'BtnEdit.Enabled = True
                'BtnCetak.Enabled = True
                'TampilDO()
                BtnSimpan.Enabled = False


                TNoDo.Text = ""
                TidDtOrder.Text = ""
                TIDKlien.Text = ""
                TKlien.Text = ""
                TIDBrand.Text = ""
                TBrand.Text = ""
                TPenerima.Text = ""
                TProyek.Text = ""
                DTDeadlineKI.Format = DateTimePickerFormat.Custom
                DTDeadlineKI.CustomFormat = "dd/MM/yyyy"
                DTTanggal.Format = DateTimePickerFormat.Custom
                DTTanggal.CustomFormat = "dd/MM/yyyy"
                SURVEI.Checked = False
                TProyek.Enabled = False
                SURVEI.Enabled = False

                BtnSimpanToko.Enabled = False
                BtnHapusPenerima.Enabled = False

                MsgBox(" Data Toko Berhasil Disimpan!..", MsgBoxStyle.Information, "Information")
        End Select
    End Sub

    Private Sub BtnHapusPenerima_Click(sender As Object, e As EventArgs) Handles BtnHapusPenerima.Click
        Dim I As Integer
        Dim ada As Boolean
        Dim sql2 As String
        Dim brs, jmldt As Integer
        ada = False
        jmldt = 0
        Select Case Proses
            Case "entry"
                ListKota.BeginUpdate() ' Turn off the ListView
                For I = ListKota.Items.Count - 1 To 0 Step -1
                    If ListKota.Items(I).Checked = True Then
                        ada = True
                        brs = I
                        jmldt = jmldt + 1
                        ListKota.Items.RemoveAt(I)

                    End If
                Next I
                If ada = False Then
                    MsgBox("Pilih Datanya yang mau dihapus !!", MsgBoxStyle.Information)
                End If
                ListKota.EndUpdate()
            Case "edit"

                ListKota.BeginUpdate() ' Turn off the ListView

                For I = ListKota.Items.Count - 1 To 0 Step -1
                    If ListKota.Items(I).Checked = True Then
                        ada = True
                        brs = I
                        jmldt = jmldt + 1
                    End If
                Next I
                If ada = False Then
                    MsgBox("Tidak ada data yang akan di EDIT, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
                    ListKota.Focus()
                    Exit Sub
                End If
                If jmldt > 1 Then
                    MsgBox("Hanya 1(satu) data yg bisa di-EDIT !!...", MsgBoxStyle.Information, "Information")
                    ListKota.Focus()
                    Exit Sub
                End If

                For Each item As ListViewItem In ListKota.CheckedItems
                    GGVM_conn()
                    sql2 = "DELETE FROM prd_kirim_dataorder WHERE idkirim = ?"
                    cmd = New OdbcCommand
                    With cmd
                        .CommandText = (sql2)
                        .Parameters.Add("@idkirim", OdbcType.BigInt).Value = Convert.ToInt32(item.SubItems(4).Text)
                        .Connection = conn
                    End With
                    dr = cmd.ExecuteReader
                    Console.WriteLine(cmd.CommandText.ToString)
                    While dr.Read
                        Console.WriteLine(dr(0))
                        Console.WriteLine()
                    End While
                    Console.ReadLine()
                    conn.Close()
                    dr = Nothing
                    cmd = Nothing

                    MsgBox("Penerima Berhasil diHapus")
                    TampilPenerima()
                Next
                TampilPenerima()
                ListKota.EndUpdate()
        End Select

    End Sub

    Private Sub CDist_CheckedChanged(sender As Object, e As EventArgs) Handles CDist.CheckedChanged
        If CDist.Checked = True Then
            CToko.Checked = False
            TPenerima.Focus()
            TPenerima.Text = ""
            GridPanel.Refresh()
            GridPanel.DataSource = Nothing
        End If
    End Sub
    Private Sub CToko_CheckedChanged(sender As Object, e As EventArgs) Handles CToko.CheckedChanged
        If CToko.Checked = True Then
            CDist.Checked = False
            TPenerima.Focus()
            TPenerima.Text = ""
            GridPanel.Refresh()
            GridPanel.DataSource = Nothing
        End If
    End Sub

    Private Sub TPenerima_KeyPress(sender As Object, e As KeyPressEventArgs) Handles TPenerima.KeyPress
        Dim s As String

        If e.KeyChar = Convert.ToChar(32) Or e.KeyChar = Convert.ToChar(127) Then
        Else
            Me.Cursor = Cursors.WaitCursor

            GridPanel.DataSource = Nothing
            s = ""
            If CDist.Checked = True Then

                GGVM_conn()
                s = s & " select a.distributor, if (c.toko is null,'',c.toko)as toko,  "
                s = s & " a.iddist, if (b.idtoko is null,'0',b.idtoko)as idtoko, a.kota "
                s = s & " from distributor a "
                s = s & " left join prd_trans_toko b on a.iddist = b.iddist "
                s = s & " left join prd_toko c on c.idtoko = b.idtoko "
                s = s & " where a.distributor like '%" & TPenerima.Text & "%' "
            ElseIf CToko.Checked = True Then
                GGVM_conn()
                s = s & " select if (c.distributor is null,'',c.distributor) as distributor,a.toko ,if(c.iddist is null, '0',c.iddist) as iddist ,  a.idtoko,  d.kota "
                s = s & " from prd_toko a "
                s = s & " left join prd_trans_toko b on a.idtoko = b.idtoko "
                s = s & " left join distributor c on c.iddist = b.iddist "
                s = s & " left join kota d on d.idkota = a.idkota "
                s = s & " where a.toko like '%" & TPenerima.Text & "%' "
            End If
            da = New OdbcDataAdapter(s, conn)
            ds = New DataSet
            ds.Clear()
            da.Fill(ds, "y")
            GridPanel.DataSource = ds.Tables("y")
            GridPanel.Refresh()

            'GGVM_conn_close()
            GridPanel.Columns(0).Width = 150
            GridPanel.Columns(1).Width = 150
            GridPanel.Columns(2).Width = 1
            GridPanel.Columns(3).Width = 1
            GridPanel.Columns(4).Width = 100
            Me.Cursor = Cursors.Default
        End If
        GGVM_conn_close()
    End Sub

    Private Sub GridPanel_CellContentClick(sender As Object, e As DataGridViewCellEventArgs) Handles GridPanel.CellContentClick

    End Sub

    Private Sub GridPanel_DoubleClick(sender As Object, e As EventArgs) Handles GridPanel.DoubleClick
        Dim i As Integer
        Select Case Proses
            Case "entry"
                i = GridPanel.CurrentRow.Index
                If i < (GridPanel.RowCount) - 1 Then
                    Dim newItem As New ListViewItem
                    newItem.Text = GridPanel.Rows.Item(i).Cells(0).Value
                    newItem.SubItems.Add(GridPanel.Rows.Item(i).Cells(1).Value)
                    newItem.SubItems.Add(GridPanel.Rows.Item(i).Cells(2).Value)
                    newItem.SubItems.Add(GridPanel.Rows.Item(i).Cells(3).Value)
                    ListKota.Items.Add(newItem)
                    GridPanel.ClearSelection()
                End If
            Case "edit"
                i = GridPanel.CurrentRow.Index
                If i < (GridPanel.RowCount) - 1 Then
                    TIdDist.Text = GridPanel.Rows.Item(i).Cells(2).Value
                    TidToko.Text = GridPanel.Rows.Item(i).Cells(3).Value
                    GridPanel.ClearSelection()
                End If

                Select Case MsgBox("TAMBAH Penerima pilih (YES), Batal Tambah Penerima pilih (NO) ", vbYesNoCancel, "Question")
                    Case vbYes
                        Dim c As String
                        GGVM_conn()
                        c = ""
                        c = c & " update prd_dataorder set "
                        c = c & " user_koreksi = '" & userid & "',"
                        c = c & " time_koreksi = now() "
                        c = c & " where iddtorder = '" & TidDtOrder.Text & "'"
                        cmd = New OdbcCommand(c, conn)
                        cmd.ExecuteNonQuery()

                        sql = " INSERT INTO prd_kirim_dataorder (iddtorder,iddist,idtoko) VALUES ('" & TidDtOrder.Text & "', '" & TIdDist.Text & "', '" & TidToko.Text & "')"
                        cmd = New OdbcCommand(sql, conn)
                        cmd.ExecuteNonQuery()

                        If CDist.Checked = True Then
                            MsgBox("Data Distributor sudah diSimpan !!..", MsgBoxStyle.Information, "Information")
                        End If
                        If CToko.Checked = True Then
                            MsgBox("Data Toko sudah diSimpan !!..", MsgBoxStyle.Information, "Information")
                        End If
                        TampilPenerima()
                        'GGVM_conn_close()
                    Case vbNo
                        Return
                End Select
                TampilPenerima()

        End Select
    End Sub
End Class
