Imports System.Data.Odbc

Public Class POProduksi
    Private Panel1Captured As Boolean
    Private Panel1Grabbed As Point
    Dim IdPOprd As Integer
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill the SqlDataSource asynchronously
        SqlDataSource1.FillAsync()
    End Sub

    Private Sub HeaderDetail()
        ListBarang.FullRowSelect = True
        ListBarang.MultiSelect = True
        ListBarang.View = System.Windows.Forms.View.Details
        ListBarang.CheckBoxes = True
        ListBarang.Columns.Clear()
        ListBarang.Items.Clear()
        ListBarang.Columns.Add("TOKO/BARANG", 190, HorizontalAlignment.Left)
        ListBarang.Columns.Add("KOTA", 120, HorizontalAlignment.Left)
        ListBarang.Columns.Add("DETAIL ITEM", 250, HorizontalAlignment.Left)
        ListBarang.Columns.Add("MATERIAL", 250, HorizontalAlignment.Left)
        ListBarang.Columns.Add("PANJANG", 80, HorizontalAlignment.Left)
        ListBarang.Columns.Add("LEBAR", 80, HorizontalAlignment.Left)
        ListBarang.Columns.Add("TINGGI", 80, HorizontalAlignment.Left)
        ListBarang.Columns.Add("SISI", 80, HorizontalAlignment.Left)
        ListBarang.Columns.Add("QTY", 80, HorizontalAlignment.Left)
        ListBarang.Columns.Add("iddetail", 0, HorizontalAlignment.Left)
        ListBarang.Columns.Add("iditem", 0, HorizontalAlignment.Left)
        ListBarang.Columns.Add("idtoko", 0, HorizontalAlignment.Left)
        ListBarang.Columns.Add("idtrans", 0, HorizontalAlignment.Left)
        ListBarang.Columns.Add("idbarangdet", 0, HorizontalAlignment.Left)
    End Sub
    Private Sub TampilDetail()
        Dim s As String
        Dim barangAsli As String
        Dim toko As String
        Dim tbl As New DataTable
        GGVM_conn()
        ListBarang.Items.Clear()
        s = ""
        s = s & " SELECT a.*,  IF	( isnull( c.barang ), '-', c.barang ) AS `barangdet` , IF	( isnull( c.idbarang ), '0', c.idbarang ) AS `idbarangdet` FROM view_detail_poprd a "
        s = s & " LEFT JOIN prd_trans_detailpo_produksi b on a.iddetail_prd = b.iddetail_prd "
        s = s & " LEFT JOIN barang c on c.idbarang = b.idbarang_detail "
        s = s & " where a.idpo_prd='" & IdPOprd & "'"
        cmd = New OdbcCommand(s, conn)
        dr = cmd.ExecuteReader

        ListBarang.Items.Clear()
        ListBarang.BeginUpdate()
        While dr.Read
            barangAsli = dr.Item("barang")
            toko = dr.Item("toko")
            Dim lvitem As New ListViewItem(barangAsli)
            Try
                If ListBarang.Groups.Item(toko).Header = toko Then
                    lvitem.Group = ListBarang.Groups(toko)
                    lvitem.SubItems.Add(dr.Item("kota"))
                    lvitem.SubItems.Add(dr.Item("barangdet"))
                    lvitem.SubItems.Add(dr.Item("material"))
                    lvitem.SubItems.Add(dr.Item("panjang_prd"))
                    lvitem.SubItems.Add(dr.Item("tinggi_prd"))
                    lvitem.SubItems.Add(dr.Item("lebar_prd"))
                    lvitem.SubItems.Add(dr.Item("sisi_prd").ToString)
                    lvitem.SubItems.Add(dr.Item("qty_prd"))
                    lvitem.SubItems.Add(dr.Item("iddetail_prd"))
                    lvitem.SubItems.Add(dr.Item("iditem_prd"))
                    lvitem.SubItems.Add(dr.Item("idtoko"))
                    lvitem.SubItems.Add(dr.Item("idtrans"))
                    lvitem.SubItems.Add(dr.Item("idbarangdet"))
                    ListBarang.Items.Add(lvitem)
                End If
            Catch
                ListBarang.Groups.Add(New ListViewGroup(toko, toko))
                lvitem.Group = ListBarang.Groups(toko)
                lvitem.SubItems.Add(dr.Item("kota"))
                lvitem.SubItems.Add(dr.Item("barangdet"))
                lvitem.SubItems.Add(dr.Item("material"))
                lvitem.SubItems.Add(dr.Item("panjang_prd"))
                lvitem.SubItems.Add(dr.Item("tinggi_prd"))
                lvitem.SubItems.Add(dr.Item("lebar_prd"))
                lvitem.SubItems.Add(dr.Item("sisi_prd").ToString)
                lvitem.SubItems.Add(dr.Item("qty_prd"))
                lvitem.SubItems.Add(dr.Item("iddetail_prd"))
                lvitem.SubItems.Add(dr.Item("iditem_prd"))
                lvitem.SubItems.Add(dr.Item("idtoko"))
                lvitem.SubItems.Add(dr.Item("idtrans"))
                lvitem.SubItems.Add(dr.Item("idbarangdet"))
                ListBarang.Items.Add(lvitem)
            End Try
        End While
        ListBarang.EndUpdate()
        GGVM_conn_close()
    End Sub
    Private Sub HeaderPekerja()
        ListManpower.FullRowSelect = True
        ListManpower.MultiSelect = True
        ListManpower.View = System.Windows.Forms.View.Details
        ListManpower.CheckBoxes = True
        ListManpower.Columns.Clear()
        ListManpower.Items.Clear()
        ListManpower.Columns.Add("NAMA", 250, HorizontalAlignment.Left)
        ListManpower.Columns.Add("nik", 0, HorizontalAlignment.Left)
    End Sub
    Private Sub TampilPekerja()
        Dim s As String
        Dim i As Integer
        Dim tbl As New DataTable
        GGVM_conn()
        ListManpower.Items.Clear()
        s = ""
        s = s & " select nama_ktp,nik from view_karyawanprd "
        da = New OdbcDataAdapter(s, conn)
        'ds.Clear()
        tbl = New DataTable
        tbl.Clear()
        da.Fill(tbl)

        If tbl.Rows.Count > 0 Then
            For i = 0 To tbl.Rows.Count - 1
                With ListManpower
                    .Items.Add(tbl.Rows(i)("nama_ktp"))
                    With .Items(.Items.Count - 1).SubItems
                        .Add(tbl.Rows(i)("nik"))
                    End With
                End With
            Next
        End If
        GGVM_conn_close()
    End Sub

    Private Sub BtnAddWorker_Click(sender As Object, e As EventArgs) Handles BtnAddWorker.Click
        If BtnAddWorker.Text = "SIMPAN" Then
            GGVM_conn()
            DTStart.Format = DateTimePickerFormat.Custom
            DTStart.CustomFormat = "dd/MM/yyyy"
            DTStart.Value = Now()

            LoadAktifitas()
            Dim adab, adap As Boolean
            Dim brs, brsp As Integer
            Dim jmldt, jmldtp As Integer
            adab = False
            jmldt = 0
            For i = 0 To ListBarang.Items.Count - 1
                If ListBarang.Items(i).Checked = True Then
                    adab = True
                    brs = i
                    jmldt = jmldt + 1
                End If
            Next
            If adab = False Then
                MsgBox("Tidak ada data yang akan di Proses, Pilih dulu datanya!!...", MsgBoxStyle.Information, "Information")
                ListBarang.Focus()
                Exit Sub
            End If

            LabelControl9.Text = jmldt
            adap = False
            jmldtp = 0
            For i = 0 To ListManpower.Items.Count - 1
                If ListManpower.Items(i).Checked = True Then
                    adap = True
                    brsp = i
                    jmldtp = jmldtp + 1
                End If
            Next
            If adap = False Then
                MsgBox("Tidak ada data yang akan di Proses, Pilih dulu data manpowernya!!...", MsgBoxStyle.Information, "Information")
                ListManpower.Focus()
                Exit Sub
            End If
            LabelControl8.Text = jmldtp
            GroupConfirm.Visible = True

        Else
            'ListPO.Items.Clear()
            ListBarang.Items.Clear()
            ListManpower.Items.Clear()
            ListBarang.Enabled = True
            ListManpower.Enabled = True
            'TampilPO()
            TampilPekerja()
            BtnAddWorker.Text = "SIMPAN"
            BtnExit.Text = "BATAL"
        End If
    End Sub
    Private Sub LoadAktifitas()
        GGVM_conn()
        Dim tbl As New DataTable
        sql = ""
        sql = sql & " select * from prd_aktifitas"
        da = New OdbcDataAdapter(sql, conn)
        tbl = New DataTable
        tbl.Clear()
        da.Fill(tbl)
        CheckActivitas.DataSource = tbl
        CheckActivitas.DisplayMember = "jenis_aktifitas"
        CheckActivitas.ValueMember = "idaktifitas"
        GGVM_conn_close()
    End Sub
    Private Sub BtnRefresh_Click(sender As Object, e As EventArgs) Handles BtnRefresh.Click
        DTStart.Format = DateTimePickerFormat.Custom
        DTStart.CustomFormat = "dd/MM/yyyy"
        DTStart.Value = Now()
        SqlDataSource1.FillAsync()
        ListBarang.Items.Clear()
        ListPekerja.Items.Clear()
        ListManpower.Items.Clear()
        BtnAddWorker.Enabled = False
        IdPOprd = ""
    End Sub

    Private Sub GroupConfirm_MouseDown(sender As Object, e As MouseEventArgs) Handles GroupConfirm.MouseDown
        Panel1Captured = True
        Panel1Grabbed = e.Location
    End Sub

    Private Sub GroupConfirm_MouseMove(sender As Object, e As MouseEventArgs) Handles GroupConfirm.MouseMove
        If (Panel1Captured) Then GroupConfirm.Location = GroupConfirm.Location + e.Location - Panel1Grabbed
    End Sub

    Private Sub GroupConfirm_MouseUp(sender As Object, e As MouseEventArgs) Handles GroupConfirm.MouseUp
        Panel1Captured = False
    End Sub

    Private Sub GroupConfirm_Paint(sender As Object, e As PaintEventArgs) Handles GroupConfirm.Paint
        GroupConfirm.Location = New Point(ClientSize.Width / 2 - GroupConfirm.Size.Width / 2, ClientSize.Height / 2 - GroupConfirm.Size.Height / 2)
        GroupConfirm.Anchor = AnchorStyles.None
    End Sub

    Private Sub CheckActivitas_SelectedIndexChanged(sender As Object, e As EventArgs) Handles CheckActivitas.SelectedIndexChanged

    End Sub
    Private Sub TampilDetailPekerja()
        Dim s As String
        Dim i As Integer
        Dim tbl As New DataTable

        GGVM_conn()
        ListPekerja.Items.Clear()
        'ListBarang.Items.Clear()
        s = ""
        s = s & "select * from view_prdjobassign where idpo_prd ='" & IdPOprd & "' and status='1'"
        da = New OdbcDataAdapter(s, conn)
        'ds.Clear()
        tbl = New DataTable
        tbl.Clear()
        da.Fill(tbl)
        For i = 0 To tbl.Rows.Count - 1
            Dim statuspekerjaan As String = ""
            If tbl.Rows(i)("done") = "1" Then
                statuspekerjaan = "Selesai"
            ElseIf tbl.Rows(i)("done") = "2" And IsDBNull(tbl.Rows(i)("nik_pengganti")) Then
                statuspekerjaan = "Ganti Manpower"
            ElseIf IIf(IsDBNull(tbl.Rows(i)("time_end")), "", tbl.Rows(i)("time_end")) <> "" AndAlso tbl.Rows(i)("time_temp") = "" Then
                statuspekerjaan = "Berhenti Sementara"
            ElseIf IIf(IsDBNull(tbl.Rows(i)("time_start")), "", tbl.Rows(i)("time_start")) <> "" Or IIf(IsDBNull(tbl.Rows(i)("time_temp")), "", tbl.Rows(i)("time_temp")) <> "" Then
                statuspekerjaan = "Progress"
            Else
                statuspekerjaan = "Belum Mulai"
            End If
            With ListPekerja
                .Items.Add(tbl.Rows(i)("nama_ktp"))
                With .Items(.Items.Count - 1).SubItems
                    .Add(IIf(IsDBNull(tbl.Rows(i)("jenis_aktifitas")), "", tbl.Rows(i)("jenis_aktifitas")))
                    .Add(tbl.Rows(i)("nopo"))
                    .Add(tbl.Rows(i)("toko"))
                    .Add(tbl.Rows(i)("barang"))
                    .Add(tbl.Rows(i)("tanggal_mulai"))
                    .Add(tbl.Rows(i)("nik"))
                    .Add(tbl.Rows(i)("idbarang"))
                    .Add(tbl.Rows(i)("idpo_prd"))
                    .Add(tbl.Rows(i)("idact_poprd"))
                    .Add(tbl.Rows(i)("idtrans_manpower"))
                    .Add(statuspekerjaan)
                    .Add(tbl.Rows(i)("time_start"))
                    .Add(tbl.Rows(i)("time_end"))
                    Dim dFrom As DateTime
                    Dim dTo As DateTime
                    Dim sDateFrom As String = tbl.Rows(i)("time_start")
                    Dim sDateTo As String = tbl.Rows(i)("time_end")
                    If DateTime.TryParse(sDateFrom, dFrom) AndAlso DateTime.TryParse(sDateTo, dTo) Then
                        Dim TS As TimeSpan = dTo - dFrom
                        Dim hour As Integer = TS.Hours
                        Dim mins As Integer = TS.Minutes
                        Dim secs As Integer = TS.Seconds
                        'Dim msec As Integer = TS.Milliseconds
                        Dim timeDiff As String = ((hour.ToString("00") & " JAM ") + mins.ToString("00") & " MENIT ") + secs.ToString("00") + " DETIK"
                        .Add(timeDiff)
                    End If
                End With
            End With
        Next

        GGVM_conn_close()
    End Sub
    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs) Handles SimpleButton2.Click
        TampilDetailPekerja()
    End Sub

    Private Sub GridView1_RowCellClick(sender As Object, e As DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs) Handles GridView1.RowCellClick
        IdPOprd = GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "idpo_prd").ToString()
    End Sub

    Private Sub GridView1_SelectionChanged(sender As Object, e As DevExpress.Data.SelectionChangedEventArgs) Handles GridView1.SelectionChanged
        IdPOprd = GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "idpo_prd").ToString()
    End Sub

    Private Sub BtnDaftar_Click(sender As Object, e As EventArgs) Handles BtnDaftar.Click

    End Sub

    Private Sub BtnExit_Click(sender As Object, e As EventArgs) Handles BtnExit.Click
        Me.Dispose()
    End Sub
End Class
